name = "trents-pc-site"
compatibility_date = "2025-04-01"
account_id = "db0779db1eebaa1a7061f7828b9bd04f"
workers_dev = true

compatibility_flags = ["nodejs_compat"]

main = "./.output/server/index.mjs"

rules = [{ type = "ESModule", globs = ["**/*.js", "**/*.mjs"] }]

[assets]
directory = "./.output/public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "prod-db-recipes"
database_id = "84530114-0f50-4881-9648-07597d355917"

[[r2_buckets]]
binding = 'IMAGES' # <~ valid JavaScript variable name
bucket_name = 'images'
