import { MarkovRecord, createMarkovBot } from "../strategies/markov";

const CLARENCE_CLARITY_MODEL: MarkovRecord = {
  "<|START|>": {
    Believe: 1,
    Just: 1,
    "(Healers)": 2,
    I: 9,
    And: 1,
    Yeah: 1,
    "I'll": 2,
    Beyond: 1,
    "I'm": 2,
    Preach: 1,
    As: 1,
    We: 1,
    Was: 1,
    You: 1,
    "It's": 4,
    Expect: 1,
    Talk: 1,
    Stop: 3,
    Slow: 1,
    Throw: 1,
    In: 2,
    "Can't": 1,
    The: 2,
    Out: 2,
    Can: 1,
    Testify: 1,
    Trust: 1,
    If: 1,
    "Oh,": 2,
    Have: 1,
    HD: 2,
    So: 2,
    Before: 3,
    Jumping: 2,
    Suddenly: 1,
    With: 2,
    Conceived: 1,
    When: 2,
  },
  Believe: { "<|END|>": 1, in: 4 },
  Just: { to: 2 },
  to: {
    be: 2,
    wind: 2,
    dust: 1,
    stop: 1,
    clot: 1,
    "me,": 3,
    myself: 3,
    "<|BR|>": 1,
    me: 8,
    see: 4,
    porn: 1,
    move: 4,
    lose: 4,
    die: 1,
  },
  be: { seen: 1, cute: 1, it: 2, your: 1, that: 1 },
  seen: { as: 1 },
  as: { honey: 1, a: 1, far: 1, "<|BR|>": 1 },
  honey: { "<|BR|>": 1 },
  "<|BR|>": {
    Dripping: 1,
    Just: 1,
    Flicking: 1,
    Believe: 4,
    Heathens: 2,
    Little: 1,
    Crazed: 1,
    Gold: 1,
    But: 4,
    And: 27,
    "Ah,": 1,
    "Yeah,": 1,
    Uh: 1,
    The: 1,
    "I'll": 3,
    In: 10,
    I: 43,
    A: 2,
    Where: 1,
    As: 1,
    "I'm": 11,
    Hell: 2,
    "I've": 9,
    Saviour: 1,
    All: 1,
    "Saviours,": 1,
    "'Cause": 2,
    Best: 1,
    It: 3,
    "She's": 1,
    Whatever: 2,
    Incestuous: 3,
    Late: 1,
    Life: 6,
    "We're": 6,
    "It's": 5,
    "Buck-toothed": 5,
    Atoms: 1,
    Infinite: 1,
    "I'd": 1,
    When: 11,
    Do: 2,
    "Love-pus": 1,
    Pornstruck: 1,
    Please: 1,
    "Padre,": 1,
    Absolvo: 1,
    Talk: 2,
    Waiting: 1,
    Sinking: 4,
    Got: 5,
    Trapped: 3,
    Watching: 1,
    "We'll": 1,
    You: 7,
    Reaching: 1,
    Out: 2,
    Take: 1,
    Alpha: 1,
    Tooth: 1,
    Cause: 1,
    "Oops,": 2,
    Off: 1,
    One: 1,
    Too: 1,
    At: 1,
    Court: 1,
    Infest: 1,
    Of: 1,
    Fool: 1,
    "Girl,": 1,
    "Chevrolet,": 1,
    Black: 1,
    "'Till": 1,
    If: 1,
    Living: 1,
    With: 3,
    "Oh,": 3,
    Give: 6,
    Have: 1,
    Judas: 1,
    Split: 1,
    Because: 1,
    So: 2,
    "“If": 4,
    Untruth: 2,
    Is: 6,
    Ulysses: 6,
    Before: 3,
    HD: 1,
    Has: 1,
    He: 1,
    "There's": 2,
    Lights: 1,
    Hear: 2,
    "You'll": 4,
    "You're": 3,
    Pull: 1,
    Exhausted: 1,
    Isolated: 1,
    "Let's": 2,
  },
  Dripping: { as: 1 },
  a: {
    pimp: 1,
    "tongue-tied": 1,
    thousand: 2,
    life: 6,
    screen: 1,
    "witness?": 1,
    shutdown: 1,
    wormhole: 1,
    bloodbath: 1,
    holy: 1,
    "fix”": 2,
    "fix“": 1,
    stabbing: 1,
    dream: 1,
    swollen: 1,
    minute: 4,
    "vice,": 1,
    "pile,": 1,
    truth: 1,
  },
  pimp: { spunks: 1 },
  spunks: { money: 1 },
  money: { "<|BR|>": 1 },
  cute: { and: 1 },
  and: {
    heartless: 1,
    "<|END|>": 1,
    Heaven: 2,
    your: 1,
    the: 21,
    her: 1,
    "I'll": 6,
    nail: 1,
    affect: 1,
    "you'll": 1,
    I: 6,
    a: 1,
    "achieved,": 1,
    "I'm": 2,
    succeed: 1,
    contrived: 1,
    set: 1,
  },
  heartless: { "<|BR|>": 1 },
  Flicking: { at: 1 },
  at: { a: 1, the: 4 },
  "tongue-tied": { sonnet: 1 },
  sonnet: { "<|END|>": 1 },
  "(Healers)": { And: 2 },
  And: {
    healers: 2,
    the: 2,
    then: 2,
    I: 7,
    "I-": 1,
    oh: 1,
    we: 3,
    "we'll": 1,
    in: 1,
    "you're": 1,
    die: 1,
    "there's": 3,
    "who's": 1,
    resent: 1,
    "it's": 1,
    my: 1,
    feed: 1,
  },
  healers: { "(Believe": 2 },
  "(Believe": { "in),": 2 },
  "in),": { believe: 2 },
  believe: { in: 2, me: 1 },
  in: {
    "liars!": 2,
    freedom: 4,
    the: 6,
    your: 3,
    limbo: 2,
    this: 1,
    "<|BR|>": 3,
    my: 4,
    death: 3,
    Hollywood: 2,
    a: 6,
    "a-”": 1,
    love: 1,
    apathy: 1,
  },
  "liars!": { "<|BR|>": 4 },
  freedom: { "<|BR|>": 2, "<|END|>": 2 },
  Heathens: { "(Heathens),": 2 },
  "(Heathens),": { dreamers: 2 },
  dreamers: { "(Dreamers),": 2 },
  "(Dreamers),": { all: 2 },
  all: { "liars!": 2, look: 2, judge: 1, fuck: 1, die: 1, "night,": 1 },
  I: {
    "changed,": 1,
    flaked: 1,
    will: 6,
    am: 32,
    wrote: 1,
    hang: 2,
    "say:": 1,
    "wouldn't": 1,
    ingested: 1,
    "don't": 3,
    sound: 1,
    mean: 1,
    might: 1,
    lost: 1,
    trust: 1,
    collapse: 1,
    fell: 5,
    get: 2,
    want: 1,
    have: 2,
    forgot: 1,
    can: 5,
    trip: 1,
    could: 5,
    was: 2,
    got: 2,
    "won't": 2,
    eat: 1,
    gleam: 1,
    lie: 1,
    bleed: 1,
    do: 8,
    stop: 4,
  },
  "changed,": { I: 1 },
  flaked: { "<|BR|>": 1 },
  Little: { pink: 1 },
  pink: { petals: 1 },
  petals: { off: 1 },
  off: { my: 10, "<|BR|>": 2 },
  my: {
    back: 1,
    white: 1,
    veins: 1,
    confusion: 1,
    grid: 9,
    head: 2,
    sickness: 1,
    leagues: 1,
    own: 1,
    vengeance: 3,
    legacy: 1,
    death: 2,
    heart: 1,
    sides: 1,
    imperfections: 1,
    hopes: 1,
    "plier-plucked": 1,
  },
  back: { like: 1, to: 1 },
  like: { rain: 1, game: 1, I: 1, "I'm": 1, we: 1, dust: 1 },
  rain: { "<|BR|>": 3 },
  Crazed: { "(Crazed),": 1 },
  "(Crazed),": { debased: 1 },
  debased: { "(Debased)": 1 },
  "(Debased)": { "<|BR|>": 1 },
  Gold: { pig: 1 },
  pig: { "peppered,": 1 },
  "peppered,": { strung: 1 },
  strung: { up: 1 },
  up: { like: 1, lovers: 1, "<|END|>": 1, "<|BR|>": 4 },
  game: { "<|END|>": 1 },
  the: {
    heart: 2,
    head: 2,
    falling: 2,
    shit: 2,
    same: 9,
    highest: 2,
    other: 2,
    yin: 12,
    yang: 12,
    fluoride: 1,
    tar: 1,
    blister: 1,
    avalanche: 3,
    panic: 1,
    mistrust: 1,
    loss: 1,
    times: 1,
    Bible: 1,
    "game,": 3,
    reptile: 1,
    "page,": 1,
    girl: 1,
    "girl),": 1,
    death: 1,
    thorns: 1,
    lines: 1,
    skies: 1,
    crimes: 1,
    rhymes: 1,
    "U.S.,": 1,
    weapons: 1,
    "gate,": 1,
    "<|BR|>": 2,
    theme: 1,
    "rain,": 1,
    Witch: 2,
    reptiles: 2,
    Catholics: 2,
    kiss: 1,
    best: 4,
    clouds: 1,
    spleen: 1,
    sickle: 1,
  },
  heart: { "can't": 2, "<|BR|>": 1 },
  "can't": { always: 2, ever: 1, unsee: 2 },
  always: { feel: 2, dream: 2 },
  feel: { it: 2, "it?": 6 },
  it: {
    "<|BR|>": 11,
    "genetic?": 1,
    blows: 1,
    gets: 1,
    "up,": 4,
    with: 1,
    "violent?": 6,
  },
  But: { the: 2, you: 1, I: 1 },
  head: { can: 2, "<|BR|>": 2 },
  can: { always: 2, try: 1, "tell,": 1, do: 1, you: 6, step: 4 },
  dream: { it: 2, where: 1 },
  then: { stop: 2, you: 2 },
  stop: { "dreaming,": 2, "<|BR|>": 1, me: 1, a: 4 },
  "dreaming,": { be: 2 },
  will: { "<|BR|>": 5, "<|END|>": 1 },
  Yeah: { "<|BR|>": 1 },
  "Ah,": { ooh: 1 },
  ooh: { "<|BR|>": 1 },
  "Yeah,": { yeah: 1 },
  yeah: { "<|BR|>": 1 },
  Uh: { "<|BR|>": 1 },
  "I-": { "<|END|>": 1 },
  "I'll": {
    be: 2,
    get: 1,
    fight: 1,
    slip: 1,
    take: 2,
    park: 1,
    step: 2,
    make: 4,
    give: 1,
  },
  your: {
    hired: 1,
    lungs: 1,
    early: 2,
    "<|BR|>": 2,
    lucks: 1,
    lipstick: 2,
    love: 1,
    crown: 1,
  },
  hired: { gun: 1 },
  gun: { "<|BR|>": 1 },
  The: { lump: 1, universe: 1, High: 1 },
  lump: { between: 1 },
  between: { your: 1, where: 2 },
  lungs: { "<|BR|>": 1 },
  that: {
    hunk: 1,
    infusion: 1,
    I: 2,
    "nothing-something": 2,
    "something-something": 1,
  },
  hunk: { of: 1 },
  of: {
    moulded: 1,
    Shakespeare: 1,
    "hate,": 1,
    the: 1,
    "death,": 1,
    computations: 1,
    his: 1,
  },
  moulded: { plastic: 1 },
  plastic: { "<|BR|>": 1 },
  In: { Egyptian: 1, the: 3, my: 1, silence: 6, a: 1 },
  Egyptian: { sun: 1 },
  sun: { and: 1, bleached: 1 },
  am: { hope: 18, fear: 14, the: 1 },
  hope: { "<|BR|>": 16, "<|END|>": 2 },
  fear: { "<|BR|>": 12, "<|END|>": 2, for: 2 },
  Beyond: { Mount: 1 },
  Mount: { Zion: 1 },
  Zion: { lies: 1 },
  lies: { "<|BR|>": 1 },
  A: { Southmere: 1, good: 1 },
  Southmere: { Lake: 1 },
  Lake: { "high-rise": 1 },
  "high-rise": { "<|BR|>": 1 },
  Where: { I: 1 },
  wrote: { ten: 1 },
  ten: { zillion: 1 },
  zillion: { words: 1 },
  words: { of: 1 },
  Shakespeare: { "<|BR|>": 1 },
  As: { they: 1, mortals: 1 },
  they: { hit: 1, all: 1 },
  hit: { my: 1 },
  white: { eyes: 1, sheets: 1 },
  eyes: { "<|END|>": 1 },
  "I'm": {
    in: 6,
    on: 2,
    real: 1,
    addicted: 3,
    disgusted: 1,
    sleeping: 1,
    the: 1,
    "thinking,": 1,
    bleached: 1,
    clean: 1,
    concise: 1,
  },
  falling: { rain: 2 },
  early: { grave: 2 },
  grave: { "<|BR|>": 2 },
  shit: { between: 2 },
  where: { "<|BR|>": 2, we: 1, "I'm": 1, I: 2, my: 1 },
  Hell: { and: 2 },
  Heaven: { look: 2 },
  look: { the: 5 },
  same: { "<|BR|>": 7, time: 1, "<|END|>": 1 },
  on: { the: 3, my: 2 },
  highest: { plane: 2 },
  plane: { "<|BR|>": 2 },
  "I've": { died: 2, got: 7 },
  died: { a: 2 },
  thousand: { ways: 2 },
  ways: { "<|BR|>": 2 },
  hang: { in: 2 },
  limbo: { "'cause": 2 },
  "'cause": { your: 2, I: 2 },
  Saviour: { looked: 1 },
  looked: { the: 1 },
  other: { way: 1, "<|END|>": 1 },
  way: { "<|END|>": 1, "<|BR|>": 2 },
  Preach: { "<|END|>": 1 },
  mortals: { we: 1 },
  we: { can: 2, all: 2, are: 2, look: 1, met: 1 },
  try: { "<|BR|>": 2 },
  oh: { good: 1, "<|END|>": 1 },
  good: { Lord: 1, girl: 1, "<|BR|>": 2, "<|END|>": 1 },
  Lord: { "you'll": 1 },
  "you'll": { try: 1, slip: 1 },
  you: {
    "can't": 1,
    catch: 1,
    tapped: 1,
    off: 2,
    crept: 1,
    expected: 1,
    mean: 1,
    "<|END|>": 2,
    "<|BR|>": 5,
    forgot: 2,
    is: 3,
    lap: 4,
    could: 1,
    spin: 2,
    "go,": 6,
    feel: 6,
    "clap,": 8,
    ask: 4,
  },
  ever: { offend: 1 },
  offend: { everyone: 1 },
  everyone: { "<|BR|>": 1 },
  All: { at: 1 },
  time: { "<|END|>": 1 },
  "Saviours,": { they: 1 },
  We: { all: 1 },
  judge: { the: 1 },
  are: { bound: 1, destiny: 1, the: 1 },
  bound: { to: 1 },
  wind: { up: 1, "<|BR|>": 1 },
  lovers: { "<|BR|>": 1 },
  "'Cause": { we: 1, I: 1 },
  fuck: { the: 1 },
  "we'll": { all: 1, spark: 1 },
  die: { the: 1, "<|BR|>": 2 },
  this: { finite: 1, "(Yeah)": 1, without: 3, all: 1 },
  finite: { cosmos: 1 },
  cosmos: { "<|BR|>": 1 },
  Best: { believe: 1 },
  me: {
    when: 1,
    swallowing: 4,
    "<|BR|>": 18,
    symmetry: 2,
    happiness: 2,
    sanity: 1,
    clarity: 1,
    what: 1,
    to: 8,
  },
  when: { I: 1, you: 1, to: 1 },
  "say:": { "<|END|>": 1 },
  Was: { it: 1 },
  "genetic?": { Did: 1 },
  Did: { you: 1 },
  catch: { "it?": 1 },
  "it?": { "<|BR|>": 8, "<|END|>": 1 },
  It: { "hadn't": 1, swells: 1, drips: 1 },
  "hadn't": { bled: 1 },
  bled: { until: 1 },
  until: { you: 1 },
  tapped: { it: 1 },
  "She's": { sun: 1 },
  bleached: { and: 2 },
  lucks: { in: 1 },
  Whatever: { gets: 2 },
  gets: { you: 2, dark: 1 },
  Incestuous: { love: 3 },
  love: { "<|END|>": 3, "<|BR|>": 3 },
  You: { "didn't": 1, have: 1, was: 1, got: 5 },
  "didn't": { know: 1 },
  know: { "you'd": 1, when: 1, but: 1 },
  "you'd": { get: 1 },
  get: { infected: 1, what: 1, blue: 1, a: 1, "made,": 1, bored: 1, born: 1 },
  infected: { "<|BR|>": 1 },
  Late: { night: 1 },
  night: { when: 1 },
  crept: { in: 1 },
  "wouldn't": { advocate: 1 },
  advocate: { eugenics: 1 },
  eugenics: { but: 1 },
  but: { "<|BR|>": 4, defected: 1, I: 1, the: 1, if: 4 },
  "It's": { the: 7, benign: 1, "what's": 1 },
  yin: { and: 6, "<|BR|>": 6 },
  yang: { and: 12 },
  Life: { without: 6 },
  without: { sex: 6, sin: 6, you: 3 },
  sex: { is: 6 },
  is: { a: 6, no: 3 },
  life: { without: 6 },
  sin: { "<|BR|>": 6 },
  "We're": { just: 6, flies: 1 },
  just: { "buck-toothed": 6 },
  "buck-toothed": { players: 6 },
  players: { playing: 11 },
  playing: { ourselves: 11 },
  ourselves: { out: 11 },
  out: { "<|BR|>": 8, "<|END|>": 3, in: 1 },
  "Buck-toothed": { players: 5 },
  Expect: { "I'll": 1 },
  what: { you: 1, "I'm": 1 },
  expected: { "<|BR|>": 1 },
  benign: { but: 1 },
  defected: { "<|BR|>": 1 },
  fluoride: { I: 1 },
  ingested: { "<|BR|>": 1 },
  Atoms: { to: 1 },
  dust: { "<|BR|>": 2 },
  Infinite: { love: 1 },
  "I'd": { quit: 1, best: 1 },
  quit: { but: 1 },
  "don't": { know: 1, wake: 1, want: 1, ask: 1 },
  When: { the: 1, you: 12 },
  tar: { in: 1 },
  veins: { begins: 1 },
  begins: { to: 1 },
  clot: { "<|BR|>": 1 },
  Do: { I: 1, you: 1 },
  sound: { like: 1, "<|END|>": 1 },
  mean: { "it?": 2 },
  "what's": { inside: 1 },
  inside: { the: 1 },
  blister: { "<|BR|>": 1 },
  girl: { and: 1, "(I": 1, "<|END|>": 1 },
  her: { sister: 1 },
  sister: { "<|BR|>": 1 },
  "Love-pus": { filled: 1 },
  filled: { confessor: 1 },
  confessor: { "<|BR|>": 1 },
  swells: { till: 1 },
  till: { it: 1 },
  blows: { "<|BR|>": 1 },
  Pornstruck: { absolution: 1 },
  absolution: { "<|BR|>": 1 },
  Please: { cure: 1 },
  cure: { my: 1 },
  confusion: { "<|BR|>": 1 },
  might: { need: 1 },
  need: { that: 1 },
  infusion: { "<|BR|>": 1 },
  "Padre,": { padre: 1 },
  padre: { "<|BR|>": 1 },
  Absolvo: { te: 1 },
  te: { "<|END|>": 1 },
  Talk: { to: 3 },
  "me,": { through: 1, like: 2 },
  through: { a: 2, and: 1, "(Slip": 1 },
  screen: { "<|BR|>": 1 },
  real: { "<|BR|>": 1, villains: 1 },
  destiny: { "<|BR|>": 1 },
  Waiting: { "<|BR|>": 1 },
  Sinking: { "<|END|>": 4 },
  Stop: { me: 3 },
  swallowing: { fires: 4 },
  fires: { "<|BR|>": 4 },
  addicted: { to: 3 },
  myself: { "<|BR|>": 4 },
  Got: { vindictive: 4, both: 1 },
  vindictive: { desires: 4 },
  desires: { "<|BR|>": 5 },
  got: { off: 4, one: 1, voices: 1, destructive: 1, that: 3, my: 3, bored: 1 },
  grid: { "<|BR|>": 7, "<|END|>": 2 },
  Trapped: { in: 3 },
  death: { waves: 3, "knoll,": 1, bed: 2 },
  waves: { beneath: 3 },
  beneath: { the: 3 },
  avalanche: { "<|BR|>": 3 },
  Slow: { the: 1 },
  panic: { down: 1 },
  down: { "<|BR|>": 1, my: 1, our: 1 },
  Watching: { "time-lapse": 1 },
  "time-lapse": { ghosts: 1 },
  ghosts: { "<|BR|>": 1 },
  "you're": { watching: 1 },
  watching: { flowers: 1 },
  flowers: { grow: 1 },
  grow: { "<|BR|>": 1 },
  "We'll": { scatter: 1 },
  scatter: { ashes: 1 },
  ashes: { where: 1 },
  met: { you: 1 },
  Throw: { caution: 1 },
  caution: { to: 1 },
  have: { seeds: 1, "to,": 1, to: 1 },
  seeds: { with: 1 },
  with: { new: 1, myself: 1, "us?": 1, a: 1 },
  new: { arms: 1 },
  arms: { "<|BR|>": 1 },
  Reaching: { "<|END|>": 1 },
  disgusted: { with: 1 },
  mistrust: { that: 1 },
  lost: { "<|BR|>": 1 },
  loss: { that: 1 },
  trust: { "<|BR|>": 1 },
  times: { I: 1 },
  collapse: { "<|BR|>": 1 },
  drips: { like: 1 },
  "there's": { dreams: 2, flies: 1 },
  dreams: { where: 2 },
  sleeping: { "<|BR|>": 1 },
  wake: { up: 1 },
  "Can't": { stop: 1 },
  one: { hand: 2 },
  hand: { on: 1, washing: 1 },
  Bible: { "<|BR|>": 1 },
  voices: { in: 1 },
  destructive: { desires: 1 },
  fell: { off: 5 },
  universe: { unfolds: 1 },
  unfolds: { "<|END|>": 1 },
  Out: { the: 4 },
  "game,": { please: 1, think: 2 },
  please: { take: 1, "<|END|>": 1 },
  take: { me: 3 },
  think: { "I'd": 1, I: 1 },
  best: { "<|BR|>": 1, policy: 4 },
  Take: { "two,": 1 },
  "two,": { "'cause": 1 },
  blue: { "<|BR|>": 1 },
  want: { "to,": 1, this: 1 },
  "to,": { "oh-oh,": 1, "oh-oh": 1 },
  "oh-oh,": { "oh-oh": 2 },
  "oh-oh": { "<|BR|>": 2, "<|END|>": 1 },
  Alpha: { "male,": 1 },
  "male,": { and: 1 },
  fight: { "<|BR|>": 1 },
  Tooth: { and: 1 },
  nail: { for: 1 },
  for: { nothing: 1, anything: 2, you: 1 },
  nothing: { "<|BR|>": 1 },
  slip: { through: 2 },
  affect: { you: 1 },
  Cause: { I: 1 },
  Can: { I: 1 },
  "witness?": { "Oops,": 1 },
  "Oops,": { I: 1, you: 2 },
  forgot: { my: 1, your: 2 },
  sickness: { "<|BR|>": 1 },
  lipstick: { luck: 2 },
  luck: { again: 2 },
  again: { "(Oh)": 2 },
  "(Oh)": { "<|BR|>": 1, "<|END|>": 1 },
  "who's": { with: 1 },
  "us?": { "We're": 1 },
  flies: { at: 1, in: 1 },
  reptile: { party: 1 },
  party: { "<|BR|>": 1 },
  Testify: { your: 1 },
  leagues: { of: 1 },
  "hate,": { "I'll": 1 },
  Off: { the: 1 },
  "page,": { a: 1 },
  shutdown: { "<|BR|>": 1 },
  One: { word: 1 },
  word: { "(One": 1 },
  "(One": { "word),": 1 },
  "word),": { and: 1 },
  "(Slip": { "through)": 1 },
  "through)": { "<|BR|>": 1 },
  resent: { "you,": 1 },
  "you,": { "oh-oh,": 1, "'cause": 1 },
  "(I": { am: 1 },
  "girl),": { as: 1 },
  far: { as: 1 },
  "tell,": { and: 1 },
  trip: { in: 1 },
  Too: { deep: 1 },
  deep: { down: 1 },
  own: { hole: 1 },
  hole: { "<|BR|>": 1 },
  At: { the: 1 },
  "knoll,": { uh: 1 },
  uh: { "<|END|>": 1 },
  Trust: { "us,": 1 },
  "us,": { "we're": 1, and: 1 },
  "we're": { the: 1, in: 4 },
  thorns: { in: 1 },
  crown: { "<|BR|>": 1 },
  Court: { "jesters,": 1 },
  "jesters,": { but: 1 },
  lines: { in: 1 },
  skies: { "<|BR|>": 1 },
  Infest: { "us,": 1 },
  crimes: { are: 1 },
  rhymes: { "<|BR|>": 1 },
  Of: { the: 1 },
  "U.S.,": { ask: 1 },
  ask: { the: 1, me: 9 },
  weapons: { inspectors: 1 },
  inspectors: { "<|END|>": 1 },
  "gate,": { "I'll": 1 },
  could: { "<|BR|>": 1, never: 3, "bleed,": 1, flee: 1 },
  Fool: { "you,": 1 },
  "(Yeah)": { "<|BR|>": 1 },
  "Girl,": { get: 1 },
  "made,": { and: 1 },
  park: { the: 1, "<|BR|>": 1 },
  "Chevrolet,": { "we'll": 1 },
  spark: { the: 1 },
  Black: { hearts: 1 },
  hearts: { of: 1 },
  theme: { park: 1 },
  "'Till": { it: 1 },
  dark: { "<|END|>": 1 },
  If: { living: 2 },
  living: { this: 2 },
  no: { good: 3, "<|BR|>": 1, "evil,": 1, evil: 1 },
  step: { "through,": 1, through: 1, into: 4 },
  "through,": { "I'll": 1 },
  wormhole: { and: 1 },
  bloodbath: { in: 1 },
  "rain,": { because: 1 },
  because: { "<|BR|>": 1 },
  Living: { this: 1 },
  was: { in: 2, born: 1 },
  Hollywood: { at: 2 },
  Witch: { House: 2 },
  House: { "<|BR|>": 2 },
  With: { the: 2, one: 1, my: 1, everything: 1 },
  reptiles: { and: 2 },
  Catholics: { "<|BR|>": 1, "<|END|>": 1 },
  "Oh,": { "oh,": 4, oh: 1 },
  "oh,": { and: 4 },
  make: { you: 4 },
  lap: { it: 4 },
  "up,": { "up,": 4, up: 4 },
  "nothing-something": { violence: 2 },
  violence: { I: 2 },
  never: { "know,": 2, know: 1, "die,": 1 },
  "know,": { but: 2 },
  vengeance: { coming: 3 },
  coming: { "<|END|>": 3 },
  Have: { mercy: 2 },
  mercy: { "<|BR|>": 2 },
  Give: { me: 6 },
  symmetry: { "<|BR|>": 2 },
  happiness: { "<|BR|>": 2 },
  sanity: { "<|BR|>": 1 },
  clarity: { "<|END|>": 1 },
  "something-something": { "<|BR|>": 1 },
  Judas: { you: 1 },
  HD: { "<|END|>": 1, pictures: 1, sound: 1 },
  give: { my: 1 },
  legacy: { the: 1 },
  kiss: { of: 1 },
  "death,": { watch: 1 },
  watch: { me: 1 },
  Split: { it: 1 },
  holy: { "sister's": 1 },
  "sister's": { "sledge-hammer": 1 },
  "sledge-hammer": { "<|BR|>": 1 },
  Because: { real: 1 },
  villains: { never: 1 },
  "die,": { no: 1 },
  So: { we: 1, then: 2, "don't": 1 },
  do: { this: 1, "it,": 8 },
  "night,": { girl: 1 },
  spin: { to: 2 },
  "“If": { "dishonesty's": 4 },
  "dishonesty's": { not: 4 },
  not: { the: 4 },
  policy: { "we're": 4 },
  "fix”": { "<|BR|>": 2 },
  Untruth: { blinds: 2 },
  blinds: { our: 2 },
  our: { way: 2, throats: 1 },
  "fix“": { "<|END|>": 1 },
  Before: { you: 6 },
  "go,": { can: 6 },
  Is: { it: 6 },
  "violent?": { "<|BR|>": 6 },
  Ulysses: { starts: 4, "can't": 2 },
  starts: { to: 4 },
  see: { me: 4, no: 1 },
  silence: { "<|BR|>": 3, "<|END|>": 3 },
  pictures: { "<|BR|>": 1 },
  High: { Priest: 1 },
  Priest: { of: 1 },
  computations: { "<|BR|>": 1 },
  Has: { enough: 1 },
  enough: { of: 1 },
  his: { temptations: 1 },
  temptations: { "<|BR|>": 1 },
  He: { surfs: 1 },
  surfs: { the: 1 },
  clouds: { to: 1 },
  porn: { mountain: 1 },
  mountain: { "<|BR|>": 1 },
  "thinking,": { please: 1 },
  "a-”": { "<|END|>": 1 },
  unsee: { me: 2 },
  Jumping: { on: 2 },
  bed: { "<|BR|>": 2 },
  "won't": { fear: 2 },
  anything: { "<|END|>": 2 },
  Suddenly: { "<|BR|>": 1 },
  "There's": { a: 2 },
  stabbing: { pain: 1 },
  pain: { in: 1 },
  Lights: { go: 1 },
  go: { out: 1, to: 1 },
  "it's": { over: 1 },
  over: { "<|BR|>": 1 },
  washing: { the: 1 },
  Conceived: { and: 1 },
  "achieved,": { and: 1 },
  clean: { "<|BR|>": 1 },
  eat: { the: 1 },
  spleen: { fed: 1 },
  fed: { back: 1 },
  gleam: { and: 1 },
  succeed: { "in-between": 1 },
  "in-between": { white: 1 },
  sheets: { "<|BR|>": 1 },
  lie: { next: 1 },
  next: { to: 4 },
  "bleed,": { emphysema: 1 },
  emphysema: { "<|BR|>": 1 },
  both: { feet: 1 },
  feet: { in: 1 },
  swollen: { fever: 1 },
  fever: { "<|BR|>": 1 },
  Hear: { no: 1, my: 1 },
  "evil,": { see: 1 },
  evil: { "<|BR|>": 1 },
  flee: { and: 1 },
  bleed: { for: 1 },
  "clap,": { I: 8 },
  "it,": { and: 4, but: 4 },
  into: { it: 4 },
  move: { you: 4 },
  if: { I: 4 },
  minute: { "<|BR|>": 4 },
  "You'll": { ask: 4 },
  lose: { "<|BR|>": 2, "<|END|>": 2 },
  sides: { in: 1 },
  "vice,": { "I'm": 1 },
  concise: { and: 1 },
  contrived: { "<|BR|>": 1 },
  imperfections: { run: 1 },
  run: { to: 1 },
  "pile,": { where: 1 },
  hopes: { go: 1 },
  "plier-plucked": { insecurities: 1 },
  insecurities: { "<|BR|>": 1 },
  "You're": { looking: 3 },
  looking: { godly: 3 },
  godly: { next: 3 },
  Pull: { and: 1 },
  set: { us: 1 },
  us: { free: 1 },
  free: { "<|END|>": 1 },
  born: { in: 1, "<|BR|>": 1 },
  everything: { "<|BR|>": 1 },
  Exhausted: { empathy: 1 },
  empathy: { "<|BR|>": 1 },
  bored: { "<|BR|>": 2 },
  truth: { in: 1 },
  apathy: { "<|BR|>": 1 },
  Isolated: { entropy: 1 },
  entropy: { "<|BR|>": 1 },
  "Let's": { get: 2 },
  feed: { the: 1 },
  sickle: { down: 1 },
  throats: { "<|END|>": 1 },
};

export const bot = createMarkovBot(CLARENCE_CLARITY_MODEL);
