import { MarkovRecord, createMarkovBot } from "../strategies/markov";

const JOCKSTRAP_MODEL: MarkovRecord = {
  "<|START|>": {
    Bring: 1,
    Like: 1,
    You: 2,
    Shifting: 1,
    Take: 1,
    In: 3,
    I: 16,
    For: 1,
    "Baby,": 1,
    Imagine: 1,
    Just: 2,
    "What's": 3,
    Hurting: 1,
    "Oh,": 2,
    "I'm": 4,
    If: 1,
    When: 1,
    She: 1,
    This: 1,
    Pain: 1,
    Press: 1,
    Scorpio: 1,
    "I'll": 1,
    Wishing: 1,
    Smash: 1,
    Since: 1,
    Love: 1,
    As: 1,
    We: 1,
    Happy: 1,
    The: 3,
    Supposed: 1,
    A: 1,
    My: 1,
    Do: 1,
  },
  Bring: { you: 2 },
  you: {
    to: 5,
    that: 2,
    want: 3,
    smiled: 1,
    do: 2,
    on: 2,
    know: 3,
    feel: 1,
    see: 1,
    liked: 1,
    "<|BR|>": 6,
    came: 1,
    give: 1,
    "<|END|>": 3,
    remind: 2,
    take: 1,
    still: 1,
    love: 1,
    hear: 1,
    float: 1,
    "don't": 3,
    hearing: 1,
    what: 10,
    at: 2,
    "anymore,": 1,
    need: 1,
    "-": 1,
    are: 2,
    hate: 1,
    my: 3,
    were: 1,
    have: 1,
    as: 1,
    told: 1,
    could: 2,
    so: 1,
    in: 1,
    and: 1,
    think: 1,
    can: 1,
  },
  to: {
    the: 7,
    own: 2,
    "<|BR|>": 3,
    me: 5,
    be: 2,
    mine: 1,
    feel: 2,
    know: 1,
    rest: 1,
    see: 2,
    fuck: 1,
    her: 1,
    go: 2,
    run: 1,
    Koreatown: 2,
    "you,": 1,
    write: 1,
    "me,": 1,
    Glasgow: 2,
    a: 1,
    blame: 1,
    give: 1,
    "you?": 1,
    kill: 1,
    do: 1,
    him: 1,
    nothing: 1,
    settle: 1,
    use: 1,
  },
  the: {
    apartment: 2,
    "now,": 2,
    same: 1,
    floor: 1,
    Woom: 1,
    first: 1,
    next: 1,
    night: 5,
    dark: 3,
    other: 2,
    Madonna: 1,
    third: 2,
    roof: 1,
    last: 1,
    city: 7,
    sky: 3,
    bridge: 2,
    day: 2,
    band: 1,
    darkness: 1,
    creation: 1,
    moon: 1,
    sun: 2,
    "tubes,": 1,
    problem: 2,
    red: 1,
    sticks: 1,
    bathroom: 2,
    blue: 2,
    darkest: 1,
    lump: 1,
    cord: 1,
    locked: 1,
    "—": 1,
    guys: 1,
    Greek: 1,
    board: 1,
    decor: 1,
    "moon,": 11,
    star: 13,
    road: 1,
    shore: 2,
    getaway: 1,
    hinge: 1,
    arrow: 1,
    best: 1,
    "city,": 1,
    'city",': 1,
    doors: 1,
    veranda: 1,
    mustard: 1,
    beaver: 4,
    kitchen: 1,
    plastic: 1,
    land: 1,
    "beaver's": 2,
    light: 1,
    monster: 1,
    "ceiling,": 1,
    round: 1,
    white: 1,
    only: 1,
    shower: 1,
    beating: 1,
    "bear,": 1,
    bear: 1,
    door: 1,
    penthouse: 1,
    "city?": 1,
    sink: 1,
  },
  apartment: { that: 2 },
  that: {
    "I'd": 2,
    "I'm": 2,
    seem: 1,
    I: 1,
    Glasgow: 1,
    way: 1,
    "moment,": 4,
    thing: 1,
  },
  "I'd": { like: 2, be: 1, name: 1, known: 1 },
  like: { to: 2, a: 2, it: 1, forever: 1, against: 1, the: 1 },
  own: { "<|BR|>": 3 },
  "<|BR|>": {
    Tell: 2,
    I: 38,
    "It's": 5,
    Like: 2,
    Your: 1,
    Covered: 1,
    "No,": 3,
    "\"That's": 1,
    As: 4,
    Flaunt: 1,
    Everything: 1,
    Take: 1,
    Leave: 2,
    Let: 3,
    Drop: 1,
    Stop: 2,
    Step: 2,
    See: 4,
    Best: 2,
    Lean: 4,
    Bring: 1,
    Tapped: 1,
    Get: 2,
    Never: 2,
    "(Girl,": 1,
    "(Lean": 1,
    Sonic: 1,
    And: 28,
    Do: 5,
    Thinking: 1,
    "He's": 1,
    How: 2,
    Fever: 2,
    "Dreamin'": 2,
    So: 3,
    Imagine: 1,
    Dressed: 1,
    Gabbana: 1,
    Feathеr: 1,
    Marie: 1,
    You: 6,
    Riding: 1,
    "(Get": 1,
    Come: 3,
    Want: 1,
    "(Come": 2,
    Sit: 1,
    My: 4,
    "What's": 6,
    The: 9,
    Will: 1,
    But: 11,
    "I've": 2,
    That: 4,
    Once: 1,
    Yet: 1,
    "Yeah,": 1,
    "Waiting's": 2,
    "Good,": 2,
    Hurting: 1,
    "Tower's": 1,
    On: 4,
    It: 2,
    This: 5,
    Randomly: 1,
    Grateful: 1,
    Solemn: 1,
    To: 3,
    Maybe: 1,
    Concrete: 2,
    "Should've": 1,
    Now: 1,
    Whatever: 1,
    Black: 2,
    Light: 1,
    In: 11,
    Two: 1,
    Barely: 1,
    Into: 1,
    When: 2,
    She: 2,
    With: 4,
    Hmm: 1,
    Fought: 1,
    '"You': 2,
    Fucking: 1,
    "Don't": 1,
    Her: 1,
    Hear: 1,
    Behind: 1,
    He: 1,
    Disco: 1,
    "(Hello?)": 5,
    "I'll": 3,
    Five: 1,
    "Ain't": 1,
    Comes: 1,
    "Back,": 1,
    "'Cause": 1,
    Are: 1,
    "(What?)": 1,
    Looked: 11,
    Wish: 11,
    At: 2,
    Going: 3,
    "I'm": 4,
    Every: 3,
    Broke: 1,
    Guess: 1,
    "Pull,": 1,
    If: 1,
    Gas: 1,
    Frankly: 1,
    Together: 1,
    We: 1,
    Amount: 1,
    Because: 2,
    Me: 1,
    "Always,": 1,
    Or: 2,
    Touching: 1,
    Just: 1,
    Enough: 1,
    '"Here,': 1,
    "Oh,": 2,
    '"I': 1,
    A: 1,
    "Well,": 2,
    Ugly: 1,
    Head: 1,
    Cook: 1,
    Grey: 1,
    Rose: 1,
    Ginger: 1,
    Monster: 1,
    Where: 1,
    Whilst: 1,
    "You'll": 1,
    Did: 1,
    None: 1,
    Something: 1,
  },
  Tell: { you: 2 },
  "I'm": {
    broke: 2,
    Madonna: 1,
    the: 1,
    grateful: 1,
    more: 1,
    glad: 1,
    ringed: 1,
    Lolita: 4,
    alone: 1,
    a: 3,
    not: 6,
    so: 1,
  },
  broke: { when: 2 },
  when: { "we're": 2, "he's": 1, I: 1, "I've": 1 },
  "we're": { all: 2 },
  all: {
    alone: 2,
    "about?": 3,
    these: 1,
    "about?)": 1,
    about: 2,
    the: 1,
    "power,": 1,
  },
  alone: { "<|BR|>": 5, with: 1, "<|END|>": 1 },
  I: {
    can: 3,
    played: 2,
    "couldn't": 2,
    "ain't": 1,
    believe: 3,
    like: 1,
    could: 14,
    know: 5,
    wanna: 5,
    noticed: 1,
    knew: 2,
    was: 4,
    put: 1,
    wrote: 1,
    never: 1,
    wish: 3,
    still: 1,
    think: 9,
    live: 1,
    feel: 3,
    see: 4,
    swear: 1,
    want: 1,
    said: 2,
    am: 5,
    birthed: 1,
    bought: 1,
    met: 2,
    cried: 1,
    "don't": 5,
    pass: 1,
    wished: 10,
    trust: 3,
    touch: 3,
    probably: 1,
    "thought,": 1,
    to: 2,
    sent: 3,
    ever: 1,
    tasted: 1,
    "want,": 1,
    "want?": 1,
    thought: 1,
    ran: 1,
    breathed: 1,
    believed: 1,
    told: 1,
    sat: 1,
    hate: 2,
    came: 1,
    flew: 1,
    fled: 1,
    really: 1,
    lost: 1,
    burnt: 1,
    hurt: 1,
    dragged: 1,
  },
  can: { be: 2, have: 1, manage: 1 },
  be: { a: 4, spilling: 1, great: 1, there: 2, looking: 1, "<|END|>": 1 },
  a: {
    stripper: 2,
    while: 2,
    DJ: 1,
    dancer: 1,
    carpet: 1,
    mohair: 1,
    Switch: 1,
    "g-g-gamer": 1,
    limousine: 1,
    "car,": 1,
    blue: 1,
    night: 1,
    filthy: 1,
    mustard: 1,
    "baby,": 1,
    "small,": 1,
    party: 1,
    woman: 3,
    place: 1,
    holiday: 1,
    pretty: 1,
    friend: 2,
    second: 1,
    house: 1,
    feeling: 1,
    thousand: 1,
    city: 2,
    fool: 1,
    huge: 1,
    "shower,": 1,
    Tring: 1,
    piece: 1,
  },
  stripper: { if: 2 },
  if: { you: 4, I: 2 },
  want: { me: 2, more: 1, "<|END|>": 1, the: 1, a: 1 },
  me: {
    to: 3,
    "<|BR|>": 5,
    with: 1,
    one: 1,
    on: 3,
    cry: 1,
    of: 2,
    as: 1,
    down: 1,
    still: 1,
    off: 3,
    and: 3,
    I: 1,
    up: 1,
  },
  "It's": { been: 3, Greatest: 1, you: 1 },
  been: { a: 2, "about?": 1, here: 1, caning: 1, draining: 1 },
  while: { since: 2 },
  since: { I: 2, "<|BR|>": 1 },
  played: { for: 2 },
  for: { ya: 2, "<|BR|>": 11, a: 5, her: 1, the: 1, love: 1 },
  ya: { "<|END|>": 1, "<|BR|>": 4, think: 2 },
  Like: { a: 3 },
  DJ: { "<|BR|>": 1 },
  dancer: { "<|BR|>": 1 },
  Your: { arms: 1 },
  arms: { and: 1, outstretched: 1 },
  and: {
    legs: 1,
    said: 1,
    he: 2,
    "I'll": 1,
    I: 3,
    wait: 1,
    the: 2,
    dark: 1,
    God: 1,
    everyone: 1,
    ever: 1,
    now: 1,
    left: 1,
    my: 2,
    "blood,": 2,
    blood: 1,
    wound: 1,
    "you,": 1,
    you: 1,
    soft: 1,
    drink: 1,
    him: 1,
    it: 1,
    your: 1,
    rye: 1,
    "<|BR|>": 1,
    threw: 1,
    dropped: 1,
    her: 1,
  },
  legs: { "<|BR|>": 1 },
  Covered: { in: 1 },
  in: {
    little: 1,
    her: 2,
    the: 13,
    dreams: 3,
    bluе: 1,
    pink: 1,
    a: 4,
    my: 6,
    holy: 1,
    "<|BR|>": 6,
    to: 1,
    and: 1,
    mine: 1,
    green: 1,
    sheets: 1,
    iron: 1,
    him: 1,
  },
  little: { white: 1 },
  white: { hairs: 1, morning: 1 },
  hairs: { "<|BR|>": 1 },
  carpet: { "<|BR|>": 1 },
  "No,": { like: 1, dressed: 1, pick: 1 },
  mohair: { sweater: 1 },
  sweater: { "<|BR|>": 1 },
  "\"That's": { sweet: 1 },
  sweet: { 'baby"': 1 },
  'baby"': { you: 1 },
  smiled: { and: 1 },
  said: { to: 2, it: 1, "<|BR|>": 4 },
  As: { if: 1, I: 1, his: 1, we: 2 },
  "couldn't": { have: 1, move: 1 },
  have: { said: 1, I: 1, to: 1, "<|BR|>": 1, what: 2 },
  it: {
    any: 1,
    "<|BR|>": 17,
    "safe,": 5,
    "<|END|>": 2,
    when: 2,
    "feel?": 2,
    all: 4,
    to: 1,
    ever: 1,
    does: 1,
    were: 1,
    'up"': 1,
    sink: 1,
    off: 1,
    if: 1,
    means: 1,
    said: 1,
    on: 1,
    was: 1,
    home: 1,
  },
  any: { better: 1 },
  better: { "<|END|>": 1, believe: 1 },
  You: {
    got: 1,
    wanna: 1,
    treat: 1,
    love: 1,
    tipped: 1,
    used: 1,
    checked: 1,
    opened: 1,
  },
  got: { it: 1 },
  Flaunt: { it: 1 },
  Everything: { is: 1 },
  is: {
    "good,": 1,
    one: 2,
    black: 1,
    God: 1,
    light: 1,
    wild: 1,
    it: 1,
    madness: 1,
    real: 2,
    also: 1,
    just: 1,
    poor: 1,
    love: 1,
    the: 1,
  },
  "good,": { girl: 1 },
  girl: { "<|BR|>": 8, "<|END|>": 1 },
  Take: { it: 2 },
  Leave: { it: 2 },
  Let: { him: 2, it: 1 },
  him: { know: 2, behind: 1, "<|BR|>": 4, what: 1 },
  know: {
    you: 2,
    I: 1,
    her: 1,
    what: 2,
    in: 1,
    "<|BR|>": 1,
    "who's": 1,
    myself: 3,
    who: 1,
    how: 1,
  },
  do: { care: 2, what: 1, to: 1, I: 2 },
  care: { "<|BR|>": 2 },
  Drop: { it: 1 },
  Stop: { it: 1, and: 1 },
  Step: { into: 2 },
  into: { the: 2, it: 5 },
  "now,": { girl: 2 },
  See: { it: 2, you: 2 },
  Best: { believe: 2 },
  believe: { it: 3, in: 3 },
  Lean: { into: 4 },
  "safe,": { girl: 4, "girl)": 1 },
  Shifting: { about: 1 },
  about: { in: 2, the: 1, you: 2, my: 2, like: 1 },
  her: {
    goddamn: 1,
    "<|BR|>": 2,
    Angst: 1,
    tight: 1,
    baby: 1,
    sing: 1,
    sister: 1,
    "arrow,": 1,
    sparkler: 1,
    face: 1,
    clothes: 1,
  },
  goddamn: { crochet: 1 },
  crochet: { pants: 1 },
  pants: { staring: 1 },
  staring: { at: 1 },
  at: { god: 1, me: 1, once: 1, the: 24, "me,": 1, you: 1 },
  god: { knows: 1 },
  knows: { what: 1 },
  what: {
    "<|BR|>": 2,
    you: 4,
    I: 11,
    have: 1,
    am: 1,
    if: 1,
    they: 1,
    do: 2,
    the: 1,
  },
  Tapped: { him: 1 },
  behind: { and: 1, the: 1 },
  he: { looked: 1, said: 1, sat: 1, refused: 1, heard: 1, took: 1 },
  looked: { at: 1 },
  with: {
    the: 3,
    ya: 3,
    me: 1,
    my: 1,
    "woman,": 1,
    nowhere: 1,
    your: 1,
    "<|BR|>": 1,
    it: 1,
  },
  same: { milky: 1 },
  milky: { eyes: 1 },
  eyes: { that: 1, "<|BR|>": 2, were: 1 },
  seem: { to: 1 },
  spilling: { up: 1 },
  up: { the: 1, your: 1, to: 1, and: 1 },
  floor: { "<|BR|>": 3, "<|END|>": 1 },
  Get: { a: 1, the: 1 },
  Switch: { and: 1 },
  "I'll": { connect: 1, take: 2, just: 2, smash: 1 },
  connect: { with: 1 },
  Never: { thought: 1, lonely: 1 },
  thought: { "I'd": 1, "<|BR|>": 2 },
  "g-g-gamer": { girl: 1 },
  "(Girl,": { "girl)": 1 },
  "girl)": { "<|END|>": 2 },
  "(Lean": { into: 1 },
  In: { every: 1, which: 1, the: 3, a: 2, my: 2, that: 4, city: 1 },
  every: { room: 1 },
  room: { "<|BR|>": 2 },
  Sonic: { boom: 1 },
  boom: { "<|BR|>": 1 },
  And: {
    in: 1,
    I: 1,
    maybe: 1,
    you: 4,
    truth: 1,
    hold: 1,
    "she'd": 1,
    pulled: 1,
    the: 2,
    "I'm": 1,
    love: 2,
    grief: 1,
    back: 2,
    "I'll": 1,
    your: 3,
    all: 1,
    told: 1,
    golden: 1,
    shed: 1,
    "worse,": 1,
  },
  Woom: { Room: 1 },
  Room: { "<|BR|>": 1 },
  Greatest: { "Hits,": 1 },
  "Hits,": { and: 1 },
  "ain't": { tryna: 1 },
  tryna: { hide: 1 },
  hide: { it: 1 },
  dreams: { "<|BR|>": 3 },
  Do: { "you?": 3, you: 1, ya: 2 },
  "you?": { "<|END|>": 1, "<|BR|>": 3 },
  For: { the: 1 },
  first: { time: 1 },
  time: { "<|BR|>": 2, I: 3 },
  "he's": { inside: 1 },
  inside: { "<|BR|>": 2 },
  Thinking: { about: 1 },
  next: { time: 1 },
  "He's": { coming: 1 },
  coming: { round: 1, to: 2 },
  round: { to: 1, red: 1 },
  mine: { "<|END|>": 2 },
  How: { does: 2 },
  does: { it: 2, "<|BR|>": 1 },
  "feel?": { "<|BR|>": 2 },
  Fever: { in: 2 },
  night: { "<|BR|>": 8, you: 1, walker: 1 },
  "Dreamin'": { in: 2 },
  dark: { "<|BR|>": 4, at: 1, because: 1 },
  on: { the: 12, "<|BR|>": 2, "<|END|>": 1, my: 3, and: 1, your: 1, but: 1 },
  other: { side: 2, girls: 1 },
  side: { "<|END|>": 2 },
  "Baby,": { you: 1 },
  could: { go: 1, tell: 13, be: 1, have: 1, not: 1 },
  go: { on: 1, "<|END|>": 1, "<|BR|>": 1 },
  So: { play: 1, dazzlingly: 1, blue: 1 },
  play: { me: 1 },
  one: { more: 1, "thing,": 2, night: 2 },
  more: { song: 1, than: 2 },
  song: { "<|END|>": 1 },
  Imagine: { "I'm": 2 },
  Madonna: { "<|BR|>": 2 },
  Dressed: { in: 1 },
  bluе: { "<|BR|>": 1 },
  dressed: { in: 1 },
  pink: { "<|BR|>": 2 },
  Gabbana: { "<|BR|>": 1 },
  Feathеr: { boa: 1 },
  boa: { "<|BR|>": 1 },
  Marie: { Antoinette: 1 },
  Antoinette: { "<|BR|>": 1 },
  wanna: { know: 1, see: 1, be: 3, "be?": 2 },
  Riding: { in: 1 },
  limousine: { "<|END|>": 1 },
  Just: { wanted: 1, twice: 1, three: 1 },
  wanted: { to: 1 },
  feel: { what: 1, inside: 1, the: 2, sick: 1, that: 1, it: 1 },
  "(Get": { a: 1 },
  "car,": { "ride)": 1 },
  "ride)": { "<|BR|>": 1 },
  Come: { to: 3 },
  third: { floor: 2 },
  Want: { you: 1 },
  my: {
    mind: 2,
    best: 1,
    good: 1,
    friend: 2,
    back: 2,
    head: 2,
    stomach: 1,
    eggshell: 1,
    chest: 1,
    "own,": 1,
    own: 1,
    "hair,": 1,
    ear: 1,
    throat: 1,
    patio: 1,
    life: 3,
    neck: 1,
    eyes: 1,
    heart: 3,
    eye: 1,
    arm: 1,
    arms: 1,
    "snake-suit": 1,
    "room,": 1,
    room: 1,
    face: 1,
  },
  mind: { "<|BR|>": 2 },
  "(Come": { "on,": 2 },
  "on,": { "baby,": 2 },
  "baby,": { "speedy,": 1, baby: 1, "I'd": 1, and: 1 },
  "speedy,": { "quick)": 1 },
  "quick)": { "<|BR|>": 1 },
  Sit: { with: 1 },
  roof: { top: 1 },
  top: { "<|BR|>": 1 },
  see: { what: 1, through: 1, "it,": 1, the: 1, "<|BR|>": 3, you: 2, her: 1 },
  through: { your: 1, "<|BR|>": 1 },
  your: {
    eyes: 2,
    neck: 1,
    phone: 1,
    man: 1,
    knees: 1,
    thigh: 1,
    fingers: 1,
    face: 1,
    'money"': 1,
  },
  baby: { "blue)": 1, weight: 1, grabbed: 1, "<|END|>": 1, "beaver,": 1 },
  "blue)": { "<|BR|>": 1 },
  "What's": { it: 3, the: 1, this: 2, missing: 3 },
  "about?": { "<|BR|>": 3, "(What's": 1 },
  My: { friend: 1, good: 1, organs: 1, homing: 1, head: 1 },
  friend: { "<|BR|>": 5, of: 1, in: 1 },
  last: { four: 1, "forever,": 1 },
  four: { years: 1, eggs: 1 },
  years: { been: 1 },
  good: { friend: 2, "friend,": 2 },
  noticed: { "you,": 1 },
  "you,": { yes: 1, '"Yes,"': 1, cause: 1, and: 1 },
  yes: { "<|BR|>": 1 },
  The: {
    hostess: 1,
    space: 1,
    baby: 1,
    days: 1,
    love: 1,
    city: 1,
    doors: 1,
    hideous: 1,
    Dutch: 1,
    beaver: 1,
    only: 1,
    bear: 1,
  },
  hostess: { "<|BR|>": 1 },
  knew: { you: 1, "<|BR|>": 1, a: 1 },
  liked: { me: 1 },
  was: {
    waited: 1,
    on: 1,
    pink: 1,
    you: 1,
    warm: 1,
    alone: 1,
    "ice,": 1,
    "<|END|>": 2,
    frying: 1,
    taking: 1,
    flooding: 1,
    the: 2,
    "me?": 1,
  },
  waited: { on: 1 },
  put: { it: 1 },
  rest: { with: 1 },
  best: { "-": 1, I: 1 },
  "-": { my: 1, what: 1 },
  Will: { it: 1 },
  ever: { "end?": 1, "<|BR|>": 1, have: 1 },
  "end?": { "<|BR|>": 1 },
  wrote: { all: 1 },
  these: { songs: 1 },
  songs: { about: 1 },
  maybe: { you: 1 },
  came: { through: 1, out: 1, "home,": 1 },
  But: { I: 2, also: 2, you: 1, pain: 1, what: 2, not: 1, the: 1, only: 1 },
  never: { knew: 1, broken: 1, know: 1 },
  "I've": { been: 2, loved: 1 },
  here: { "before,": 1 },
  "before,": { too: 1 },
  too: { "<|END|>": 3, "<|BR|>": 1 },
  "(What's": { it: 1 },
  "about?)": { "<|BR|>": 1 },
  That: { wonderful: 1, would: 1, we: 1, "I'm": 1 },
  wonderful: { night: 1 },
  give: { to: 1, you: 1 },
  treat: { me: 1 },
  Once: { in: 1 },
  blue: { moon: 1, and: 1, linoleum: 1, "tiled,": 1, water: 1 },
  moon: { "<|BR|>": 2 },
  wish: { "you'd": 1, I: 1, "I'd": 1 },
  "you'd": { just: 1 },
  just: { touch: 1, love: 1, see: 2, kissing: 1 },
  touch: { me: 1, myself: 3 },
  Yet: { I: 1 },
  still: { sit: 1, come: 1, "<|BR|>": 1 },
  sit: { and: 1, in: 1 },
  wait: { "<|BR|>": 1 },
  "Yeah,": { I: 1 },
  think: { "we'd": 1, you: 3, of: 4, I: 2, or: 1, that: 1, "that's": 2 },
  "we'd": { be: 1 },
  great: { "together,": 1 },
  "together,": { too: 1 },
  Hurting: { is: 2 },
  "thing,": { but: 2 },
  but: { "<|BR|>": 2, "it's": 1, it: 1, I: 1, look: 1 },
  "Waiting's": { "another,": 2 },
  "another,": { yeah: 2 },
  yeah: { "<|BR|>": 2 },
  this: { all: 2 },
  "Good,": { good: 2 },
  "friend,": { too: 2 },
  live: { in: 1 },
  city: { "<|BR|>": 6, I: 1, like: 1, light: 1, life: 1, hell: 1 },
  "Tower's": { blue: 1 },
  sky: { is: 1, "<|BR|>": 1, called: 1 },
  black: { "<|BR|>": 1, frying: 1 },
  "it,": { "it's": 1, better: 1 },
  "it's": { on: 1, you: 1, dark: 1, me: 1, all: 1 },
  back: { "<|BR|>": 2, down: 2, to: 1 },
  On: { my: 1, the: 3 },
  It: { makes: 1, is: 1 },
  makes: { me: 1 },
  cry: { "<|BR|>": 1 },
  This: { European: 1, red: 1, is: 3, "isn't": 1 },
  European: { "air,": 1 },
  "air,": { I: 1 },
  swear: { it: 1 },
  Randomly: { "I'm": 1 },
  grateful: { for: 1 },
  Grateful: { for: 1 },
  Solemn: { night: 1 },
  walker: { "<|BR|>": 1 },
  To: { our: 1, fuck: 1, think: 1 },
  our: { telephone: 1 },
  telephone: { talker: 1 },
  talker: { "<|BR|>": 1 },
  Maybe: { "it's": 1 },
  "Oh,": { one: 2, what: 1, way: 1 },
  bridge: { we: 2 },
  we: { stood: 2, "lie,": 1, lay: 1, would: 1, "thought,": 1, thought: 1 },
  stood: { "<|BR|>": 2 },
  Concrete: { over: 2 },
  over: { water: 2 },
  water: { "<|BR|>": 2, was: 1, falling: 1 },
  remind: { me: 2 },
  of: {
    the: 5,
    "Italy,": 2,
    Spain: 2,
    its: 1,
    light: 1,
    lord: 1,
    acid: 1,
    "<|BR|>": 1,
    my: 1,
    friends: 1,
    I: 1,
    her: 1,
    other: 1,
    anything: 1,
    "me?": 1,
    you: 1,
  },
  also: { of: 2, growth: 1 },
  day: { "<|BR|>": 2 },
  "Italy,": { champagne: 2 },
  champagne: { "<|BR|>": 2 },
  Spain: { "<|END|>": 2 },
  there: { "<|BR|>": 2, just: 1 },
  than: { my: 2 },
  head: { "<|BR|>": 1, "<|END|>": 1, hit: 1 },
  "Should've": { meant: 1 },
  meant: { it: 1 },
  Now: { "I'm": 1 },
  glad: { you: 1 },
  take: { me: 1, you: 2 },
  as: { I: 1, "me,": 1, you: 1 },
  am: { "<|BR|>": 2, so: 2, "alone,": 1, I: 1 },
  Whatever: { shape: 1 },
  shape: { with: 1 },
  "woman,": { man: 1 },
  man: { "<|BR|>": 1, and: 1 },
  Black: { or: 1, spots: 1 },
  or: { "blue,": 1, "worse,": 1, dream: 1 },
  "blue,": { a: 1 },
  filthy: { cheat: 1 },
  cheat: { I: 1 },
  come: { to: 1 },
  band: { "<|BR|>": 1 },
  Light: { and: 1 },
  once: { "<|BR|>": 1 },
  lonely: { in: 1 },
  holy: { metronomy: 1 },
  metronomy: { "<|BR|>": 1 },
  dazzlingly: { dark: 1 },
  because: { of: 1, it: 1 },
  its: { bright: 1 },
  bright: { "<|BR|>": 1, "<|END|>": 1 },
  truth: { is: 1 },
  God: { and: 1, is: 1 },
  light: { "<|BR|>": 3, "<|END|>": 1, the: 1 },
  space: { behind: 1 },
  which: { the: 1 },
  darkness: { depends: 1 },
  depends: { on: 1 },
  creation: { of: 1 },
  Two: { sides: 1 },
  sides: { of: 1 },
  spots: { on: 1 },
  sun: { "<|END|>": 1, streams: 1 },
  sick: { "<|BR|>": 1 },
  organs: { bob: 1 },
  bob: { about: 1 },
  mustard: { "mist,": 1, air: 1 },
  "mist,": { in: 1 },
  stomach: { vase: 1 },
  vase: { "<|BR|>": 1, of: 1 },
  Barely: { connected: 1 },
  connected: { by: 1 },
  by: { the: 1 },
  "tubes,": { but: 1 },
  eggshell: { "<|END|>": 1 },
  If: { it: 2 },
  were: { a: 1, to: 1, bright: 1 },
  name: { her: 1 },
  Angst: { "<|BR|>": 1 },
  hold: { her: 1 },
  tight: { in: 1 },
  chest: { "<|BR|>": 1 },
  "she'd": { "grow,": 1 },
  "grow,": { from: 1 },
  from: { a: 1, my: 4 },
  "small,": { hard: 1 },
  hard: { stone: 1, "'cause": 1 },
  stone: { "<|BR|>": 1 },
  Into: { my: 1 },
  "own,": { the: 1 },
  problem: { my: 1, was: 1 },
  would: { disease: 1, last: 1 },
  disease: { "everything,": 1 },
  "everything,": { and: 1 },
  everyone: { "<|END|>": 1 },
  When: { I: 2, "I'm": 1 },
  birthed: { "her,": 1 },
  "her,": { I: 2 },
  bought: { the: 1 },
  red: { "<|BR|>": 1, cord: 1, table: 1 },
  met: { "her,": 1, was: 1 },
  cried: { the: 1 },
  sticks: { for: 1, to: 1 },
  She: { came: 1, tortured: 1, pulled: 1 },
  out: { "crimson,": 1, in: 1, west: 1 },
  "crimson,": { on: 1 },
  bathroom: { floor: 1, "<|END|>": 1 },
  With: { her: 1, the: 1, linked: 1, my: 1 },
  weight: { she: 1 },
  she: { kept: 1, said: 1, believes: 3, hit: 1 },
  kept: { me: 1, house: 1 },
  down: { "<|BR|>": 1, to: 2 },
  linoleum: { "<|BR|>": 1 },
  Hmm: { "<|END|>": 1 },
  tortured: { me: 1 },
  darkest: { spell: 1 },
  spell: { "<|BR|>": 1 },
  Fought: { about: 1 },
  forever: { and: 1, "-ever": 1 },
  pulled: { on: 1, the: 1 },
  "hair,": { whispered: 1 },
  whispered: { in: 1 },
  ear: { "<|BR|>": 1 },
  '"You': { fucking: 1, poor: 1 },
  fucking: { love: 1 },
  love: { "<|BR|>": 2, to: 1, it: 1, is: 1, with: 1, you: 1, cannot: 1, of: 1 },
  fuck: { "<|BR|>": 1, it: 1 },
  'up"': { "<|BR|>": 1 },
  Fucking: { listen: 1 },
  listen: { to: 1 },
  sing: { "<|END|>": 1 },
  cord: { "<|BR|>": 2 },
  grabbed: { the: 1 },
  lump: { in: 1 },
  throat: { "<|BR|>": 1 },
  wild: { she: 1 },
  madness: { "<|BR|>": 1 },
  "Don't": { you: 1 },
  Her: { "love's": 1 },
  "love's": { gonna: 1 },
  gonna: { change: 1 },
  change: { "<|BR|>": 1 },
  Hear: { "it,": 1 },
  sink: { in: 1, "<|BR|>": 1 },
  his: { titanic: 1 },
  titanic: { rises: 1 },
  rises: { "<|BR|>": 1 },
  streams: { in: 1 },
  hear: { heart: 1 },
  heart: { of: 1, "<|END|>": 3, "<|BR|>": 1 },
  lord: { "<|BR|>": 1 },
  Behind: { the: 1 },
  locked: { door: 1 },
  door: { "<|BR|>": 1, even: 1 },
  ringed: { around: 1 },
  around: { your: 1, "<|BR|>": 1 },
  neck: { "<|BR|>": 1, and: 1 },
  He: { "sinks,": 1 },
  "sinks,": { you: 1 },
  float: { "<|BR|>": 1 },
  "don't": {
    "<|END|>": 2,
    rock: 1,
    speak: 1,
    feel: 1,
    hurt: 1,
    know: 1,
    wanna: 1,
  },
  Pain: { is: 1 },
  real: { "<|BR|>": 2 },
  pain: { is: 1 },
  growth: { "<|BR|>": 1 },
  grief: { is: 1 },
  nowhere: { to: 1 },
  Press: { Y: 1 },
  Y: { for: 1 },
  party: { "<|BR|>": 1 },
  Disco: { sticks: 1 },
  run: { around: 1 },
  "(Hello?)": { "I'm": 4, "<|BR|>": 1 },
  Lolita: { "<|BR|>": 3, "<|END|>": 1 },
  Koreatown: { "<|BR|>": 2 },
  Five: { stars: 1 },
  stars: { but: 1 },
  "Ain't": { hard: 1 },
  "'cause": { it: 1 },
  Comes: { naturally: 1 },
  naturally: { "<|END|>": 1 },
  Scorpio: { "<|BR|>": 1 },
  "—": { off: 1 },
  off: { my: 1, that: 1, with: 1, or: 1, "<|BR|>": 2 },
  patio: { "<|BR|>": 1 },
  rock: { with: 1 },
  speak: { to: 1 },
  guys: { that: 1 },
  pass: { in: 1 },
  Greek: { quarter: 1 },
  quarter: { "<|BR|>": 1 },
  "Back,": { back: 1 },
  board: { with: 1 },
  decor: { "<|BR|>": 1 },
  "'Cause": { you: 1 },
  Are: { you: 1 },
  hearing: { "that?": 1 },
  "that?": { "<|BR|>": 1 },
  "(What?)": { "<|BR|>": 1 },
  pick: { up: 1 },
  phone: { "<|BR|>": 1 },
  "who's": { calling: 1 },
  calling: { "<|END|>": 1 },
  tell: { you: 12, "<|BR|>": 1 },
  wished: { for: 10 },
  Looked: { at: 11 },
  "moon,": { press: 11 },
  press: { X: 11 },
  X: { at: 11 },
  star: { "<|BR|>": 12, "<|END|>": 1 },
  Wish: { I: 11 },
  At: { the: 2 },
  myself: { "<|BR|>": 9, when: 1 },
  Going: { "'round": 3 },
  "'round": { again: 3 },
  again: { "<|BR|>": 3 },
  trust: { myself: 3 },
  woman: { she: 3 },
  believes: { in: 3 },
  Every: { time: 3 },
  missing: { from: 3 },
  life: { "<|END|>": 4 },
  Wishing: { I: 1 },
  road: { "<|BR|>": 1 },
  tipped: { me: 1 },
  Glasgow: { could: 1, "<|BR|>": 2 },
  place: { to: 1 },
  '"Yes,"': { but: 1 },
  probably: { "won't": 1 },
  "won't": { "<|BR|>": 1 },
  used: { to: 1 },
  write: { to: 1 },
  "me,": { "baby,": 1, you: 1, "you,": 1, 'city"': 1 },
  now: { you: 1 },
  not: { coming: 2, me: 1, provide: 1, myself: 1, "well,": 1, well: 2 },
  shore: { "<|BR|>": 2 },
  checked: { in: 1 },
  holiday: { spa: 1 },
  spa: { "<|BR|>": 1 },
  Broke: { it: 1 },
  left: { in: 1, with: 1 },
  getaway: { car: 1 },
  car: { "<|BR|>": 1 },
  days: { went: 1 },
  went: { on: 1 },
  "thought,": { '"This': 1, we: 1 },
  '"This': { is: 1 },
  poor: { 'rapport"': 1, baby: 1 },
  'rapport"': { "<|BR|>": 1 },
  Guess: { I: 1 },
  way: { about: 1, out: 1 },
  "anymore,": { baby: 1 },
  "moment,": { I: 3, "I'm": 1 },
  so: { alone: 3, "<|BR|>": 2, you: 1 },
  "alone,": { so: 1 },
  Smash: { a: 1 },
  pretty: { vase: 1 },
  acid: { "<|BR|>": 1 },
  smash: { it: 1 },
  need: { someone: 1 },
  someone: { to: 1 },
  blame: { "<|BR|>": 1 },
  "Pull,": { "pull,": 1 },
  "pull,": { pull: 1 },
  pull: { from: 1 },
  means: { you: 1 },
  hurt: { anymore: 1, "<|BR|>": 1 },
  anymore: { "<|END|>": 1 },
  twice: { "we've": 1 },
  "we've": { spoken: 2 },
  spoken: { since: 1, trice: 1 },
  Gas: { and: 1 },
  "blood,": { and: 2 },
  blood: { "<|BR|>": 1 },
  are: { full: 1, left: 1, the: 1 },
  full: { of: 2 },
  who: { you: 1, I: 1 },
  hate: { "<|END|>": 1, you: 1, your: 1 },
  sent: { you: 3 },
  Since: { then: 1 },
  then: { "we've": 1 },
  trice: { "<|BR|>": 1 },
  kill: { me: 1 },
  "worse,": { "yourself?": 1, I: 1 },
  "yourself?": { "<|BR|>": 1 },
  wound: { "him;": 1 },
  "him;": { do: 1 },
  cause: { "it's": 1 },
  Love: { forever: 1 },
  "-ever": { "<|BR|>": 1 },
  Frankly: { never: 1 },
  broken: { "<|BR|>": 1 },
  Together: { "-ether": 1 },
  "-ether": { "<|END|>": 1 },
  "lie,": { wet: 1 },
  wet: { and: 1 },
  soft: { "<|BR|>": 1 },
  linked: { limbs: 1 },
  limbs: { "<|BR|>": 1 },
  knees: { make: 1 },
  make: { the: 1 },
  hinge: { "<|BR|>": 1 },
  We: { are: 1, sit: 1 },
  Amount: { to: 1 },
  nothing: { "<|BR|>": 1 },
  lay: { there: 1 },
  kissing: { "<|END|>": 1 },
  arrow: { of: 1 },
  eye: { "<|BR|>": 1 },
  Because: { I: 1, of: 1 },
  Me: { as: 1 },
  "Always,": { a: 1 },
  friends: { "<|BR|>": 1 },
  Or: { if: 1, think: 1 },
  they: { want: 1 },
  drink: { "<|BR|>": 1 },
  cannot: { stop: 1 },
  stop: { for: 1 },
  second: { "<|BR|>": 1 },
  Touching: { "me,": 1 },
  three: { nights: 1 },
  nights: { and: 1 },
  arm: { on: 1 },
  thigh: { "<|BR|>": 1 },
  fingers: { in: 1 },
  Happy: { "looking,": 1 },
  "looking,": { yellow: 1 },
  yellow: { in: 1 },
  green: { "<|BR|>": 1 },
  sister: { before: 1 },
  before: { she: 1 },
  hit: { thirteen: 1, the: 2 },
  thirteen: { "<|BR|>": 1 },
  "arrow,": { her: 1 },
  sparkler: { girl: 1 },
  house: { full: 1, with: 1 },
  girls: { "<|BR|>": 1 },
  Enough: { for: 1 },
  feeling: { to: 1 },
  settle: { "<|END|>": 1 },
  tasted: { the: 1 },
  "city,": { ate: 1 },
  ate: { out: 1 },
  called: { up: 1 },
  '"Here,': { look: 1 },
  look: { at: 2 },
  'city"': { "<|BR|>": 1 },
  "want,": { what: 1 },
  "want?": { "<|BR|>": 1 },
  '"I': { suddenly: 1 },
  suddenly: { want: 1 },
  'city",': { I: 1 },
  A: { thousand: 1, taxi: 1 },
  thousand: { thoughts: 1, times: 1 },
  thoughts: { for: 1 },
  times: { "<|BR|>": 1 },
  loved: { in: 1 },
  sheets: { with: 1 },
  opened: { the: 1 },
  doors: { "<|BR|>": 1, onto: 1 },
  onto: { the: 2 },
  veranda: { "<|BR|>": 1 },
  ran: { outside: 1 },
  outside: { in: 1 },
  air: { "<|BR|>": 1 },
  outstretched: { to: 1 },
  breathed: { in: 1 },
  fool: { "<|BR|>": 1 },
  only: { because: 1, thing: 2 },
  homing: { guide: 1 },
  guide: { "<|BR|>": 1 },
  told: { me: 1, you: 1, him: 1 },
  provide: { "<|BR|>": 1 },
  "Well,": { I: 2 },
  believed: { you: 1 },
  "forever,": { we: 1 },
  face: { was: 1, and: 2, "<|BR|>": 1, in: 1 },
  warm: { and: 1 },
  known: { "<|BR|>": 1 },
  hideous: { monster: 1 },
  monster: { and: 1, kept: 1, was: 1 },
  beaver: { "<|BR|>": 2, on: 1, was: 1, saw: 1 },
  Ugly: { monster: 1 },
  Head: { scraping: 1 },
  scraping: { like: 1 },
  against: { the: 2 },
  kitchen: { ceiling: 1 },
  ceiling: { "<|BR|>": 1 },
  Cook: { for: 1 },
  plastic: { dishes: 1 },
  dishes: { "<|BR|>": 1 },
  land: { was: 1 },
  "ice,": { ice: 1 },
  ice: { "<|BR|>": 1 },
  Grey: { morning: 1 },
  morning: { light: 1, "sunlight,": 1 },
  "beaver,": { 'beaver,"': 1 },
  'beaver,"': { he: 1 },
  sat: { on: 2 },
  "beaver's": { face: 2 },
  frying: { four: 1, pan: 1 },
  eggs: { in: 1 },
  huge: { black: 1 },
  pan: { "<|BR|>": 1 },
  golden: { buckwheat: 1 },
  buckwheat: { and: 1 },
  rye: { in: 1 },
  iron: { "toaster,": 1 },
  "toaster,": { hit: 1 },
  "ceiling,": { onto: 1 },
  "tiled,": { err: 1 },
  err: { "<|BR|>": 1 },
  Dutch: { china: 1 },
  china: { plates: 1 },
  plates: { on: 1 },
  table: { "<|BR|>": 1 },
  Rose: { petal: 1 },
  petal: { "jam,": 1 },
  "jam,": { "orange-lemon": 1 },
  "orange-lemon": { "<|BR|>": 1 },
  Ginger: { "marmalade,": 1 },
  "marmalade,": { blossom: 1 },
  blossom: { "jelly,": 1 },
  "jelly,": { jelly: 1 },
  jelly: { "<|BR|>": 1 },
  taking: { a: 1 },
  "shower,": { he: 1 },
  refused: { to: 1 },
  use: { shower: 1 },
  shower: { curtains: 1, water: 1 },
  curtains: { "<|BR|>": 1 },
  flooding: { the: 1 },
  thing: { the: 1, he: 1, was: 1 },
  saw: { was: 1 },
  "sunlight,": { and: 1 },
  heard: { was: 1 },
  falling: { like: 1 },
  beating: { heart: 1 },
  Monster: { to: 1 },
  "bear,": { '"So': 1 },
  '"So': { "it's": 1 },
  "power,": { "power,": 1, power: 1 },
  power: { "can't": 1 },
  "can't": { sleep: 1 },
  sleep: { "<|BR|>": 1 },
  dream: { of: 1 },
  anything: { else: 1 },
  else: { "<|BR|>": 1 },
  'money"': { "<|BR|>": 1 },
  bear: { "raged,": 1, forgot: 1 },
  "raged,": { the: 1 },
  forgot: { himself: 1 },
  himself: { and: 1, against: 1 },
  threw: { himself: 1 },
  even: { harder: 1 },
  harder: { "<|END|>": 1 },
  "home,": { "yeah,": 1 },
  "yeah,": { I: 1 },
  flew: { in: 1 },
  fled: { the: 1 },
  penthouse: { suite: 1 },
  suite: { "<|BR|>": 1 },
  shed: { my: 1 },
  "snake-suit": { skin: 1 },
  skin: { "<|BR|>": 1 },
  "isn't": { a: 1 },
  Where: { is: 1 },
  "city?": { "<|END|>": 1 },
  Supposed: { to: 1 },
  looking: { for: 1 },
  west: { I: 1 },
  taxi: { picked: 1 },
  picked: { me: 1 },
  dropped: { me: 1 },
  Whilst: { he: 1 },
  took: { in: 1 },
  clothes: { off: 1 },
  "room,": { in: 1 },
  move: { on: 1 },
  really: { scared: 1 },
  scared: { him: 1 },
  lost: { a: 1 },
  caning: { "<|BR|>": 1 },
  draining: { "<|BR|>": 1 },
  Tring: { trick: 1 },
  trick: { "<|END|>": 1 },
  "well,": { oh: 1 },
  oh: { "I'm": 1 },
  well: { "<|BR|>": 1, "<|END|>": 1 },
  burnt: { my: 1 },
  hell: { "<|BR|>": 1 },
  "You'll": { never: 1 },
  how: { deep: 1 },
  deep: { I: 1 },
  dragged: { it: 1 },
  home: { so: 1 },
  piece: { of: 1 },
  "me?": { "<|BR|>": 2 },
  Did: { you: 1 },
  "that's": { who: 1, where: 1 },
  "be?": { "<|BR|>": 2 },
  None: { of: 1 },
  manage: { me: 1 },
  where: { I: 1 },
  Something: { I: 1 },
};

export const bot = createMarkovBot(JOCKSTRAP_MODEL);
