/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/+__root'
import { Route as WordsImport } from './routes/+words'
import { Route as TwoHardThingsImport } from './routes/+two-hard-things'
import { Route as TicTacToeImport } from './routes/+tic-tac-toe'
import { Route as SokobanImport } from './routes/+sokoban'
import { Route as SecretWordImport } from './routes/+secret-word'
import { Route as NestedRouteImport } from './routes/+nested/+route'
import { Route as JesusImport } from './routes/+jesus'
import { Route as IsoImport } from './routes/+iso'
import { Route as GbImport } from './routes/+gb'
import { Route as FontExplorerRouteImport } from './routes/+font-explorer/+route'
import { Route as FakerImport } from './routes/+faker'
import { Route as DemoImport } from './routes/+demo'
import { Route as CvImport } from './routes/+cv'
import { Route as ChadgdpRouteImport } from './routes/+chadgdp/+route'
import { Route as CalendarImport } from './routes/+calendar'
import { Route as BoggleImport } from './routes/+boggle'
import { Route as IndexImport } from './routes/+index'
import { Route as OsWin98Import } from './routes/+os/+win98'
import { Route as OsSonomaImport } from './routes/+os/+sonoma'
import { Route as OsIosImport } from './routes/+os/+ios'
import { Route as FontExplorerHexImport } from './routes/+font-explorer/+hex'
import { Route as PantryIndexImport } from './routes/+pantry/+index'
import { Route as FontExplorerIndexImport } from './routes/+font-explorer/+index'
import { Route as FontExplorerTablesFFTMImport } from './routes/+font-explorer/+tables/+FFTM'
import { Route as FontExplorerTablesUnknownTableImport } from './routes/+font-explorer/+tables/+$unknownTable'
import { Route as PantryBooksIndexImport } from './routes/+pantry/+books/+index'
import { Route as FontExplorerTablesIndexImport } from './routes/+font-explorer/+tables/+index'
import { Route as PantryRecipesRecipeIdEditRouteImport } from './routes/+pantry/+recipes/+$recipeId/+edit/+route'
import { Route as PantryRecipesRecipeIdIndexImport } from './routes/+pantry/+recipes/+$recipeId/+index'
import { Route as PantryBooksBookIdIndexImport } from './routes/+pantry/+books/+$bookId/+index'

// Create/Update Routes

const WordsRoute = WordsImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => rootRoute,
} as any)

const TwoHardThingsRoute = TwoHardThingsImport.update({
  id: '/two-hard-things',
  path: '/two-hard-things',
  getParentRoute: () => rootRoute,
} as any)

const TicTacToeRoute = TicTacToeImport.update({
  id: '/tic-tac-toe',
  path: '/tic-tac-toe',
  getParentRoute: () => rootRoute,
} as any)

const SokobanRoute = SokobanImport.update({
  id: '/sokoban',
  path: '/sokoban',
  getParentRoute: () => rootRoute,
} as any)

const SecretWordRoute = SecretWordImport.update({
  id: '/secret-word',
  path: '/secret-word',
  getParentRoute: () => rootRoute,
} as any)

const NestedRouteRoute = NestedRouteImport.update({
  id: '/nested',
  path: '/nested',
  getParentRoute: () => rootRoute,
} as any)

const JesusRoute = JesusImport.update({
  id: '/jesus',
  path: '/jesus',
  getParentRoute: () => rootRoute,
} as any)

const IsoRoute = IsoImport.update({
  id: '/iso',
  path: '/iso',
  getParentRoute: () => rootRoute,
} as any)

const GbRoute = GbImport.update({
  id: '/gb',
  path: '/gb',
  getParentRoute: () => rootRoute,
} as any)

const FontExplorerRouteRoute = FontExplorerRouteImport.update({
  id: '/font-explorer',
  path: '/font-explorer',
  getParentRoute: () => rootRoute,
} as any)

const FakerRoute = FakerImport.update({
  id: '/faker',
  path: '/faker',
  getParentRoute: () => rootRoute,
} as any)

const DemoRoute = DemoImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRoute,
} as any)

const CvRoute = CvImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRoute,
} as any)

const ChadgdpRouteRoute = ChadgdpRouteImport.update({
  id: '/chadgdp',
  path: '/chadgdp',
  getParentRoute: () => rootRoute,
} as any)

const CalendarRoute = CalendarImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRoute,
} as any)

const BoggleRoute = BoggleImport.update({
  id: '/boggle',
  path: '/boggle',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OsWin98Route = OsWin98Import.update({
  id: '/os/win98',
  path: '/os/win98',
  getParentRoute: () => rootRoute,
} as any)

const OsSonomaRoute = OsSonomaImport.update({
  id: '/os/sonoma',
  path: '/os/sonoma',
  getParentRoute: () => rootRoute,
} as any)

const OsIosRoute = OsIosImport.update({
  id: '/os/ios',
  path: '/os/ios',
  getParentRoute: () => rootRoute,
} as any)

const FontExplorerHexRoute = FontExplorerHexImport.update({
  id: '/hex',
  path: '/hex',
  getParentRoute: () => FontExplorerRouteRoute,
} as any)

const PantryIndexRoute = PantryIndexImport.update({
  id: '/pantry/',
  path: '/pantry/',
  getParentRoute: () => rootRoute,
} as any)

const FontExplorerIndexRoute = FontExplorerIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FontExplorerRouteRoute,
} as any)

const FontExplorerTablesFFTMRoute = FontExplorerTablesFFTMImport.update({
  id: '/tables/FFTM',
  path: '/tables/FFTM',
  getParentRoute: () => FontExplorerRouteRoute,
} as any)

const FontExplorerTablesUnknownTableRoute =
  FontExplorerTablesUnknownTableImport.update({
    id: '/tables/$unknownTable',
    path: '/tables/$unknownTable',
    getParentRoute: () => FontExplorerRouteRoute,
  } as any)

const PantryBooksIndexRoute = PantryBooksIndexImport.update({
  id: '/pantry/books/',
  path: '/pantry/books/',
  getParentRoute: () => rootRoute,
} as any)

const FontExplorerTablesIndexRoute = FontExplorerTablesIndexImport.update({
  id: '/tables/',
  path: '/tables/',
  getParentRoute: () => FontExplorerRouteRoute,
} as any)

const PantryRecipesRecipeIdEditRouteRoute =
  PantryRecipesRecipeIdEditRouteImport.update({
    id: '/pantry/recipes/$recipeId/edit',
    path: '/pantry/recipes/$recipeId/edit',
    getParentRoute: () => rootRoute,
  } as any)

const PantryRecipesRecipeIdIndexRoute = PantryRecipesRecipeIdIndexImport.update(
  {
    id: '/pantry/recipes/$recipeId/',
    path: '/pantry/recipes/$recipeId/',
    getParentRoute: () => rootRoute,
  } as any,
)

const PantryBooksBookIdIndexRoute = PantryBooksBookIdIndexImport.update({
  id: '/pantry/books/$bookId/',
  path: '/pantry/books/$bookId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/boggle': {
      id: '/boggle'
      path: '/boggle'
      fullPath: '/boggle'
      preLoaderRoute: typeof BoggleImport
      parentRoute: typeof rootRoute
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarImport
      parentRoute: typeof rootRoute
    }
    '/chadgdp': {
      id: '/chadgdp'
      path: '/chadgdp'
      fullPath: '/chadgdp'
      preLoaderRoute: typeof ChadgdpRouteImport
      parentRoute: typeof rootRoute
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvImport
      parentRoute: typeof rootRoute
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoImport
      parentRoute: typeof rootRoute
    }
    '/faker': {
      id: '/faker'
      path: '/faker'
      fullPath: '/faker'
      preLoaderRoute: typeof FakerImport
      parentRoute: typeof rootRoute
    }
    '/font-explorer': {
      id: '/font-explorer'
      path: '/font-explorer'
      fullPath: '/font-explorer'
      preLoaderRoute: typeof FontExplorerRouteImport
      parentRoute: typeof rootRoute
    }
    '/gb': {
      id: '/gb'
      path: '/gb'
      fullPath: '/gb'
      preLoaderRoute: typeof GbImport
      parentRoute: typeof rootRoute
    }
    '/iso': {
      id: '/iso'
      path: '/iso'
      fullPath: '/iso'
      preLoaderRoute: typeof IsoImport
      parentRoute: typeof rootRoute
    }
    '/jesus': {
      id: '/jesus'
      path: '/jesus'
      fullPath: '/jesus'
      preLoaderRoute: typeof JesusImport
      parentRoute: typeof rootRoute
    }
    '/nested': {
      id: '/nested'
      path: '/nested'
      fullPath: '/nested'
      preLoaderRoute: typeof NestedRouteImport
      parentRoute: typeof rootRoute
    }
    '/secret-word': {
      id: '/secret-word'
      path: '/secret-word'
      fullPath: '/secret-word'
      preLoaderRoute: typeof SecretWordImport
      parentRoute: typeof rootRoute
    }
    '/sokoban': {
      id: '/sokoban'
      path: '/sokoban'
      fullPath: '/sokoban'
      preLoaderRoute: typeof SokobanImport
      parentRoute: typeof rootRoute
    }
    '/tic-tac-toe': {
      id: '/tic-tac-toe'
      path: '/tic-tac-toe'
      fullPath: '/tic-tac-toe'
      preLoaderRoute: typeof TicTacToeImport
      parentRoute: typeof rootRoute
    }
    '/two-hard-things': {
      id: '/two-hard-things'
      path: '/two-hard-things'
      fullPath: '/two-hard-things'
      preLoaderRoute: typeof TwoHardThingsImport
      parentRoute: typeof rootRoute
    }
    '/words': {
      id: '/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof WordsImport
      parentRoute: typeof rootRoute
    }
    '/font-explorer/': {
      id: '/font-explorer/'
      path: '/'
      fullPath: '/font-explorer/'
      preLoaderRoute: typeof FontExplorerIndexImport
      parentRoute: typeof FontExplorerRouteImport
    }
    '/pantry/': {
      id: '/pantry/'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryIndexImport
      parentRoute: typeof rootRoute
    }
    '/font-explorer/hex': {
      id: '/font-explorer/hex'
      path: '/hex'
      fullPath: '/font-explorer/hex'
      preLoaderRoute: typeof FontExplorerHexImport
      parentRoute: typeof FontExplorerRouteImport
    }
    '/os/ios': {
      id: '/os/ios'
      path: '/os/ios'
      fullPath: '/os/ios'
      preLoaderRoute: typeof OsIosImport
      parentRoute: typeof rootRoute
    }
    '/os/sonoma': {
      id: '/os/sonoma'
      path: '/os/sonoma'
      fullPath: '/os/sonoma'
      preLoaderRoute: typeof OsSonomaImport
      parentRoute: typeof rootRoute
    }
    '/os/win98': {
      id: '/os/win98'
      path: '/os/win98'
      fullPath: '/os/win98'
      preLoaderRoute: typeof OsWin98Import
      parentRoute: typeof rootRoute
    }
    '/font-explorer/tables/': {
      id: '/font-explorer/tables/'
      path: '/tables'
      fullPath: '/font-explorer/tables'
      preLoaderRoute: typeof FontExplorerTablesIndexImport
      parentRoute: typeof FontExplorerRouteImport
    }
    '/pantry/books/': {
      id: '/pantry/books/'
      path: '/pantry/books'
      fullPath: '/pantry/books'
      preLoaderRoute: typeof PantryBooksIndexImport
      parentRoute: typeof rootRoute
    }
    '/font-explorer/tables/$unknownTable': {
      id: '/font-explorer/tables/$unknownTable'
      path: '/tables/$unknownTable'
      fullPath: '/font-explorer/tables/$unknownTable'
      preLoaderRoute: typeof FontExplorerTablesUnknownTableImport
      parentRoute: typeof FontExplorerRouteImport
    }
    '/font-explorer/tables/FFTM': {
      id: '/font-explorer/tables/FFTM'
      path: '/tables/FFTM'
      fullPath: '/font-explorer/tables/FFTM'
      preLoaderRoute: typeof FontExplorerTablesFFTMImport
      parentRoute: typeof FontExplorerRouteImport
    }
    '/pantry/books/$bookId/': {
      id: '/pantry/books/$bookId/'
      path: '/pantry/books/$bookId'
      fullPath: '/pantry/books/$bookId'
      preLoaderRoute: typeof PantryBooksBookIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/pantry/recipes/$recipeId/': {
      id: '/pantry/recipes/$recipeId/'
      path: '/pantry/recipes/$recipeId'
      fullPath: '/pantry/recipes/$recipeId'
      preLoaderRoute: typeof PantryRecipesRecipeIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/pantry/recipes/$recipeId/edit': {
      id: '/pantry/recipes/$recipeId/edit'
      path: '/pantry/recipes/$recipeId/edit'
      fullPath: '/pantry/recipes/$recipeId/edit'
      preLoaderRoute: typeof PantryRecipesRecipeIdEditRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface FontExplorerRouteRouteChildren {
  FontExplorerIndexRoute: typeof FontExplorerIndexRoute
  FontExplorerHexRoute: typeof FontExplorerHexRoute
  FontExplorerTablesIndexRoute: typeof FontExplorerTablesIndexRoute
  FontExplorerTablesUnknownTableRoute: typeof FontExplorerTablesUnknownTableRoute
  FontExplorerTablesFFTMRoute: typeof FontExplorerTablesFFTMRoute
}

const FontExplorerRouteRouteChildren: FontExplorerRouteRouteChildren = {
  FontExplorerIndexRoute: FontExplorerIndexRoute,
  FontExplorerHexRoute: FontExplorerHexRoute,
  FontExplorerTablesIndexRoute: FontExplorerTablesIndexRoute,
  FontExplorerTablesUnknownTableRoute: FontExplorerTablesUnknownTableRoute,
  FontExplorerTablesFFTMRoute: FontExplorerTablesFFTMRoute,
}

const FontExplorerRouteRouteWithChildren =
  FontExplorerRouteRoute._addFileChildren(FontExplorerRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boggle': typeof BoggleRoute
  '/calendar': typeof CalendarRoute
  '/chadgdp': typeof ChadgdpRouteRoute
  '/cv': typeof CvRoute
  '/demo': typeof DemoRoute
  '/faker': typeof FakerRoute
  '/font-explorer': typeof FontExplorerRouteRouteWithChildren
  '/gb': typeof GbRoute
  '/iso': typeof IsoRoute
  '/jesus': typeof JesusRoute
  '/nested': typeof NestedRouteRoute
  '/secret-word': typeof SecretWordRoute
  '/sokoban': typeof SokobanRoute
  '/tic-tac-toe': typeof TicTacToeRoute
  '/two-hard-things': typeof TwoHardThingsRoute
  '/words': typeof WordsRoute
  '/font-explorer/': typeof FontExplorerIndexRoute
  '/pantry': typeof PantryIndexRoute
  '/font-explorer/hex': typeof FontExplorerHexRoute
  '/os/ios': typeof OsIosRoute
  '/os/sonoma': typeof OsSonomaRoute
  '/os/win98': typeof OsWin98Route
  '/font-explorer/tables': typeof FontExplorerTablesIndexRoute
  '/pantry/books': typeof PantryBooksIndexRoute
  '/font-explorer/tables/$unknownTable': typeof FontExplorerTablesUnknownTableRoute
  '/font-explorer/tables/FFTM': typeof FontExplorerTablesFFTMRoute
  '/pantry/books/$bookId': typeof PantryBooksBookIdIndexRoute
  '/pantry/recipes/$recipeId': typeof PantryRecipesRecipeIdIndexRoute
  '/pantry/recipes/$recipeId/edit': typeof PantryRecipesRecipeIdEditRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boggle': typeof BoggleRoute
  '/calendar': typeof CalendarRoute
  '/chadgdp': typeof ChadgdpRouteRoute
  '/cv': typeof CvRoute
  '/demo': typeof DemoRoute
  '/faker': typeof FakerRoute
  '/gb': typeof GbRoute
  '/iso': typeof IsoRoute
  '/jesus': typeof JesusRoute
  '/nested': typeof NestedRouteRoute
  '/secret-word': typeof SecretWordRoute
  '/sokoban': typeof SokobanRoute
  '/tic-tac-toe': typeof TicTacToeRoute
  '/two-hard-things': typeof TwoHardThingsRoute
  '/words': typeof WordsRoute
  '/font-explorer': typeof FontExplorerIndexRoute
  '/pantry': typeof PantryIndexRoute
  '/font-explorer/hex': typeof FontExplorerHexRoute
  '/os/ios': typeof OsIosRoute
  '/os/sonoma': typeof OsSonomaRoute
  '/os/win98': typeof OsWin98Route
  '/font-explorer/tables': typeof FontExplorerTablesIndexRoute
  '/pantry/books': typeof PantryBooksIndexRoute
  '/font-explorer/tables/$unknownTable': typeof FontExplorerTablesUnknownTableRoute
  '/font-explorer/tables/FFTM': typeof FontExplorerTablesFFTMRoute
  '/pantry/books/$bookId': typeof PantryBooksBookIdIndexRoute
  '/pantry/recipes/$recipeId': typeof PantryRecipesRecipeIdIndexRoute
  '/pantry/recipes/$recipeId/edit': typeof PantryRecipesRecipeIdEditRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/boggle': typeof BoggleRoute
  '/calendar': typeof CalendarRoute
  '/chadgdp': typeof ChadgdpRouteRoute
  '/cv': typeof CvRoute
  '/demo': typeof DemoRoute
  '/faker': typeof FakerRoute
  '/font-explorer': typeof FontExplorerRouteRouteWithChildren
  '/gb': typeof GbRoute
  '/iso': typeof IsoRoute
  '/jesus': typeof JesusRoute
  '/nested': typeof NestedRouteRoute
  '/secret-word': typeof SecretWordRoute
  '/sokoban': typeof SokobanRoute
  '/tic-tac-toe': typeof TicTacToeRoute
  '/two-hard-things': typeof TwoHardThingsRoute
  '/words': typeof WordsRoute
  '/font-explorer/': typeof FontExplorerIndexRoute
  '/pantry/': typeof PantryIndexRoute
  '/font-explorer/hex': typeof FontExplorerHexRoute
  '/os/ios': typeof OsIosRoute
  '/os/sonoma': typeof OsSonomaRoute
  '/os/win98': typeof OsWin98Route
  '/font-explorer/tables/': typeof FontExplorerTablesIndexRoute
  '/pantry/books/': typeof PantryBooksIndexRoute
  '/font-explorer/tables/$unknownTable': typeof FontExplorerTablesUnknownTableRoute
  '/font-explorer/tables/FFTM': typeof FontExplorerTablesFFTMRoute
  '/pantry/books/$bookId/': typeof PantryBooksBookIdIndexRoute
  '/pantry/recipes/$recipeId/': typeof PantryRecipesRecipeIdIndexRoute
  '/pantry/recipes/$recipeId/edit': typeof PantryRecipesRecipeIdEditRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boggle'
    | '/calendar'
    | '/chadgdp'
    | '/cv'
    | '/demo'
    | '/faker'
    | '/font-explorer'
    | '/gb'
    | '/iso'
    | '/jesus'
    | '/nested'
    | '/secret-word'
    | '/sokoban'
    | '/tic-tac-toe'
    | '/two-hard-things'
    | '/words'
    | '/font-explorer/'
    | '/pantry'
    | '/font-explorer/hex'
    | '/os/ios'
    | '/os/sonoma'
    | '/os/win98'
    | '/font-explorer/tables'
    | '/pantry/books'
    | '/font-explorer/tables/$unknownTable'
    | '/font-explorer/tables/FFTM'
    | '/pantry/books/$bookId'
    | '/pantry/recipes/$recipeId'
    | '/pantry/recipes/$recipeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boggle'
    | '/calendar'
    | '/chadgdp'
    | '/cv'
    | '/demo'
    | '/faker'
    | '/gb'
    | '/iso'
    | '/jesus'
    | '/nested'
    | '/secret-word'
    | '/sokoban'
    | '/tic-tac-toe'
    | '/two-hard-things'
    | '/words'
    | '/font-explorer'
    | '/pantry'
    | '/font-explorer/hex'
    | '/os/ios'
    | '/os/sonoma'
    | '/os/win98'
    | '/font-explorer/tables'
    | '/pantry/books'
    | '/font-explorer/tables/$unknownTable'
    | '/font-explorer/tables/FFTM'
    | '/pantry/books/$bookId'
    | '/pantry/recipes/$recipeId'
    | '/pantry/recipes/$recipeId/edit'
  id:
    | '__root__'
    | '/'
    | '/boggle'
    | '/calendar'
    | '/chadgdp'
    | '/cv'
    | '/demo'
    | '/faker'
    | '/font-explorer'
    | '/gb'
    | '/iso'
    | '/jesus'
    | '/nested'
    | '/secret-word'
    | '/sokoban'
    | '/tic-tac-toe'
    | '/two-hard-things'
    | '/words'
    | '/font-explorer/'
    | '/pantry/'
    | '/font-explorer/hex'
    | '/os/ios'
    | '/os/sonoma'
    | '/os/win98'
    | '/font-explorer/tables/'
    | '/pantry/books/'
    | '/font-explorer/tables/$unknownTable'
    | '/font-explorer/tables/FFTM'
    | '/pantry/books/$bookId/'
    | '/pantry/recipes/$recipeId/'
    | '/pantry/recipes/$recipeId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoggleRoute: typeof BoggleRoute
  CalendarRoute: typeof CalendarRoute
  ChadgdpRouteRoute: typeof ChadgdpRouteRoute
  CvRoute: typeof CvRoute
  DemoRoute: typeof DemoRoute
  FakerRoute: typeof FakerRoute
  FontExplorerRouteRoute: typeof FontExplorerRouteRouteWithChildren
  GbRoute: typeof GbRoute
  IsoRoute: typeof IsoRoute
  JesusRoute: typeof JesusRoute
  NestedRouteRoute: typeof NestedRouteRoute
  SecretWordRoute: typeof SecretWordRoute
  SokobanRoute: typeof SokobanRoute
  TicTacToeRoute: typeof TicTacToeRoute
  TwoHardThingsRoute: typeof TwoHardThingsRoute
  WordsRoute: typeof WordsRoute
  PantryIndexRoute: typeof PantryIndexRoute
  OsIosRoute: typeof OsIosRoute
  OsSonomaRoute: typeof OsSonomaRoute
  OsWin98Route: typeof OsWin98Route
  PantryBooksIndexRoute: typeof PantryBooksIndexRoute
  PantryBooksBookIdIndexRoute: typeof PantryBooksBookIdIndexRoute
  PantryRecipesRecipeIdIndexRoute: typeof PantryRecipesRecipeIdIndexRoute
  PantryRecipesRecipeIdEditRouteRoute: typeof PantryRecipesRecipeIdEditRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoggleRoute: BoggleRoute,
  CalendarRoute: CalendarRoute,
  ChadgdpRouteRoute: ChadgdpRouteRoute,
  CvRoute: CvRoute,
  DemoRoute: DemoRoute,
  FakerRoute: FakerRoute,
  FontExplorerRouteRoute: FontExplorerRouteRouteWithChildren,
  GbRoute: GbRoute,
  IsoRoute: IsoRoute,
  JesusRoute: JesusRoute,
  NestedRouteRoute: NestedRouteRoute,
  SecretWordRoute: SecretWordRoute,
  SokobanRoute: SokobanRoute,
  TicTacToeRoute: TicTacToeRoute,
  TwoHardThingsRoute: TwoHardThingsRoute,
  WordsRoute: WordsRoute,
  PantryIndexRoute: PantryIndexRoute,
  OsIosRoute: OsIosRoute,
  OsSonomaRoute: OsSonomaRoute,
  OsWin98Route: OsWin98Route,
  PantryBooksIndexRoute: PantryBooksIndexRoute,
  PantryBooksBookIdIndexRoute: PantryBooksBookIdIndexRoute,
  PantryRecipesRecipeIdIndexRoute: PantryRecipesRecipeIdIndexRoute,
  PantryRecipesRecipeIdEditRouteRoute: PantryRecipesRecipeIdEditRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "+__root.tsx",
      "children": [
        "/",
        "/boggle",
        "/calendar",
        "/chadgdp",
        "/cv",
        "/demo",
        "/faker",
        "/font-explorer",
        "/gb",
        "/iso",
        "/jesus",
        "/nested",
        "/secret-word",
        "/sokoban",
        "/tic-tac-toe",
        "/two-hard-things",
        "/words",
        "/pantry/",
        "/os/ios",
        "/os/sonoma",
        "/os/win98",
        "/pantry/books/",
        "/pantry/books/$bookId/",
        "/pantry/recipes/$recipeId/",
        "/pantry/recipes/$recipeId/edit"
      ]
    },
    "/": {
      "filePath": "+index.tsx"
    },
    "/boggle": {
      "filePath": "+boggle.tsx"
    },
    "/calendar": {
      "filePath": "+calendar.tsx"
    },
    "/chadgdp": {
      "filePath": "+chadgdp/+route.tsx"
    },
    "/cv": {
      "filePath": "+cv.tsx"
    },
    "/demo": {
      "filePath": "+demo.tsx"
    },
    "/faker": {
      "filePath": "+faker.tsx"
    },
    "/font-explorer": {
      "filePath": "+font-explorer/+route.tsx",
      "children": [
        "/font-explorer/",
        "/font-explorer/hex",
        "/font-explorer/tables/",
        "/font-explorer/tables/$unknownTable",
        "/font-explorer/tables/FFTM"
      ]
    },
    "/gb": {
      "filePath": "+gb.tsx"
    },
    "/iso": {
      "filePath": "+iso.tsx"
    },
    "/jesus": {
      "filePath": "+jesus.tsx"
    },
    "/nested": {
      "filePath": "+nested/+route.tsx"
    },
    "/secret-word": {
      "filePath": "+secret-word.tsx"
    },
    "/sokoban": {
      "filePath": "+sokoban.tsx"
    },
    "/tic-tac-toe": {
      "filePath": "+tic-tac-toe.tsx"
    },
    "/two-hard-things": {
      "filePath": "+two-hard-things.tsx"
    },
    "/words": {
      "filePath": "+words.tsx"
    },
    "/font-explorer/": {
      "filePath": "+font-explorer/+index.tsx",
      "parent": "/font-explorer"
    },
    "/pantry/": {
      "filePath": "+pantry/+index.tsx"
    },
    "/font-explorer/hex": {
      "filePath": "+font-explorer/+hex.tsx",
      "parent": "/font-explorer"
    },
    "/os/ios": {
      "filePath": "+os/+ios.tsx"
    },
    "/os/sonoma": {
      "filePath": "+os/+sonoma.tsx"
    },
    "/os/win98": {
      "filePath": "+os/+win98.tsx"
    },
    "/font-explorer/tables/": {
      "filePath": "+font-explorer/+tables/+index.tsx",
      "parent": "/font-explorer"
    },
    "/pantry/books/": {
      "filePath": "+pantry/+books/+index.tsx"
    },
    "/font-explorer/tables/$unknownTable": {
      "filePath": "+font-explorer/+tables/+$unknownTable.tsx",
      "parent": "/font-explorer"
    },
    "/font-explorer/tables/FFTM": {
      "filePath": "+font-explorer/+tables/+FFTM.tsx",
      "parent": "/font-explorer"
    },
    "/pantry/books/$bookId/": {
      "filePath": "+pantry/+books/+$bookId/+index.tsx"
    },
    "/pantry/recipes/$recipeId/": {
      "filePath": "+pantry/+recipes/+$recipeId/+index.tsx"
    },
    "/pantry/recipes/$recipeId/edit": {
      "filePath": "+pantry/+recipes/+$recipeId/+edit/+route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
