/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordsRouteImport } from './routes/words'
import { Route as TwoHardThingsRouteImport } from './routes/two-hard-things'
import { Route as TicTacToeRouteImport } from './routes/tic-tac-toe'
import { Route as SpringRouteImport } from './routes/spring'
import { Route as SokobanRouteImport } from './routes/sokoban'
import { Route as SecretWordRouteImport } from './routes/secret-word'
import { Route as IsoRouteImport } from './routes/iso'
import { Route as GbRouteImport } from './routes/gb'
import { Route as FakerRouteImport } from './routes/faker'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CvRouteImport } from './routes/cv'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BoggleRouteImport } from './routes/boggle'
import { Route as NestedRouteRouteImport } from './routes/nested/route'
import { Route as FontExplorerRouteRouteImport } from './routes/font-explorer/route'
import { Route as ChadgdpRouteRouteImport } from './routes/chadgdp/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PixelFontIndexRouteImport } from './routes/pixel-font/index'
import { Route as PantryIndexRouteImport } from './routes/pantry/index'
import { Route as FontExplorerIndexRouteImport } from './routes/font-explorer/index'
import { Route as PixelFontVibeCodedRouteImport } from './routes/pixel-font/vibe-coded'
import { Route as OsWin98RouteImport } from './routes/os/win98'
import { Route as OsSonomaRouteImport } from './routes/os/sonoma'
import { Route as OsIos3RouteImport } from './routes/os/ios3'
import { Route as OsIosRouteImport } from './routes/os/ios'
import { Route as FontExplorerHexRouteImport } from './routes/font-explorer/hex'
import { Route as PantryBooksIndexRouteImport } from './routes/pantry/books/index'
import { Route as FontExplorerTablesIndexRouteImport } from './routes/font-explorer/tables/index'
import { Route as FontExplorerTablesFFTMRouteImport } from './routes/font-explorer/tables/FFTM'
import { Route as FontExplorerTablesUnknownTableRouteImport } from './routes/font-explorer/tables/$unknownTable'
import { Route as PantryRecipesRecipeIdIndexRouteImport } from './routes/pantry/recipes/$recipeId/index'
import { Route as PantryBooksBookIdIndexRouteImport } from './routes/pantry/books/$bookId/index'
import { Route as PantryRecipesRecipeIdEditRouteRouteImport } from './routes/pantry/recipes/$recipeId/edit/route'

const WordsRoute = WordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoHardThingsRoute = TwoHardThingsRouteImport.update({
  id: '/two-hard-things',
  path: '/two-hard-things',
  getParentRoute: () => rootRouteImport,
} as any)
const TicTacToeRoute = TicTacToeRouteImport.update({
  id: '/tic-tac-toe',
  path: '/tic-tac-toe',
  getParentRoute: () => rootRouteImport,
} as any)
const SpringRoute = SpringRouteImport.update({
  id: '/spring',
  path: '/spring',
  getParentRoute: () => rootRouteImport,
} as any)
const SokobanRoute = SokobanRouteImport.update({
  id: '/sokoban',
  path: '/sokoban',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretWordRoute = SecretWordRouteImport.update({
  id: '/secret-word',
  path: '/secret-word',
  getParentRoute: () => rootRouteImport,
} as any)
const IsoRoute = IsoRouteImport.update({
  id: '/iso',
  path: '/iso',
  getParentRoute: () => rootRouteImport,
} as any)
const GbRoute = GbRouteImport.update({
  id: '/gb',
  path: '/gb',
  getParentRoute: () => rootRouteImport,
} as any)
const FakerRoute = FakerRouteImport.update({
  id: '/faker',
  path: '/faker',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BoggleRoute = BoggleRouteImport.update({
  id: '/boggle',
  path: '/boggle',
  getParentRoute: () => rootRouteImport,
} as any)
const NestedRouteRoute = NestedRouteRouteImport.update({
  id: '/nested',
  path: '/nested',
  getParentRoute: () => rootRouteImport,
} as any)
const FontExplorerRouteRoute = FontExplorerRouteRouteImport.update({
  id: '/font-explorer',
  path: '/font-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChadgdpRouteRoute = ChadgdpRouteRouteImport.update({
  id: '/chadgdp',
  path: '/chadgdp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PixelFontIndexRoute = PixelFontIndexRouteImport.update({
  id: '/pixel-font/',
  path: '/pixel-font/',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryIndexRoute = PantryIndexRouteImport.update({
  id: '/pantry/',
  path: '/pantry/',
  getParentRoute: () => rootRouteImport,
} as any)
const FontExplorerIndexRoute = FontExplorerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FontExplorerRouteRoute,
} as any)
const PixelFontVibeCodedRoute = PixelFontVibeCodedRouteImport.update({
  id: '/pixel-font/vibe-coded',
  path: '/pixel-font/vibe-coded',
  getParentRoute: () => rootRouteImport,
} as any)
const OsWin98Route = OsWin98RouteImport.update({
  id: '/os/win98',
  path: '/os/win98',
  getParentRoute: () => rootRouteImport,
} as any)
const OsSonomaRoute = OsSonomaRouteImport.update({
  id: '/os/sonoma',
  path: '/os/sonoma',
  getParentRoute: () => rootRouteImport,
} as any)
const OsIos3Route = OsIos3RouteImport.update({
  id: '/os/ios3',
  path: '/os/ios3',
  getParentRoute: () => rootRouteImport,
} as any)
const OsIosRoute = OsIosRouteImport.update({
  id: '/os/ios',
  path: '/os/ios',
  getParentRoute: () => rootRouteImport,
} as any)
const FontExplorerHexRoute = FontExplorerHexRouteImport.update({
  id: '/hex',
  path: '/hex',
  getParentRoute: () => FontExplorerRouteRoute,
} as any)
const PantryBooksIndexRoute = PantryBooksIndexRouteImport.update({
  id: '/pantry/books/',
  path: '/pantry/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const FontExplorerTablesIndexRoute = FontExplorerTablesIndexRouteImport.update({
  id: '/tables/',
  path: '/tables/',
  getParentRoute: () => FontExplorerRouteRoute,
} as any)
const FontExplorerTablesFFTMRoute = FontExplorerTablesFFTMRouteImport.update({
  id: '/tables/FFTM',
  path: '/tables/FFTM',
  getParentRoute: () => FontExplorerRouteRoute,
} as any)
const FontExplorerTablesUnknownTableRoute =
  FontExplorerTablesUnknownTableRouteImport.update({
    id: '/tables/$unknownTable',
    path: '/tables/$unknownTable',
    getParentRoute: () => FontExplorerRouteRoute,
  } as any)
const PantryRecipesRecipeIdIndexRoute =
  PantryRecipesRecipeIdIndexRouteImport.update({
    id: '/pantry/recipes/$recipeId/',
    path: '/pantry/recipes/$recipeId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PantryBooksBookIdIndexRoute = PantryBooksBookIdIndexRouteImport.update({
  id: '/pantry/books/$bookId/',
  path: '/pantry/books/$bookId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryRecipesRecipeIdEditRouteRoute =
  PantryRecipesRecipeIdEditRouteRouteImport.update({
    id: '/pantry/recipes/$recipeId/edit',
    path: '/pantry/recipes/$recipeId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chadgdp': typeof ChadgdpRouteRoute
  '/font-explorer': typeof FontExplorerRouteRouteWithChildren
  '/nested': typeof NestedRouteRoute
  '/boggle': typeof BoggleRoute
  '/calendar': typeof CalendarRoute
  '/cv': typeof CvRoute
  '/demo': typeof DemoRoute
  '/faker': typeof FakerRoute
  '/gb': typeof GbRoute
  '/iso': typeof IsoRoute
  '/secret-word': typeof SecretWordRoute
  '/sokoban': typeof SokobanRoute
  '/spring': typeof SpringRoute
  '/tic-tac-toe': typeof TicTacToeRoute
  '/two-hard-things': typeof TwoHardThingsRoute
  '/words': typeof WordsRoute
  '/font-explorer/hex': typeof FontExplorerHexRoute
  '/os/ios': typeof OsIosRoute
  '/os/ios3': typeof OsIos3Route
  '/os/sonoma': typeof OsSonomaRoute
  '/os/win98': typeof OsWin98Route
  '/pixel-font/vibe-coded': typeof PixelFontVibeCodedRoute
  '/font-explorer/': typeof FontExplorerIndexRoute
  '/pantry': typeof PantryIndexRoute
  '/pixel-font': typeof PixelFontIndexRoute
  '/font-explorer/tables/$unknownTable': typeof FontExplorerTablesUnknownTableRoute
  '/font-explorer/tables/FFTM': typeof FontExplorerTablesFFTMRoute
  '/font-explorer/tables': typeof FontExplorerTablesIndexRoute
  '/pantry/books': typeof PantryBooksIndexRoute
  '/pantry/recipes/$recipeId/edit': typeof PantryRecipesRecipeIdEditRouteRoute
  '/pantry/books/$bookId': typeof PantryBooksBookIdIndexRoute
  '/pantry/recipes/$recipeId': typeof PantryRecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chadgdp': typeof ChadgdpRouteRoute
  '/nested': typeof NestedRouteRoute
  '/boggle': typeof BoggleRoute
  '/calendar': typeof CalendarRoute
  '/cv': typeof CvRoute
  '/demo': typeof DemoRoute
  '/faker': typeof FakerRoute
  '/gb': typeof GbRoute
  '/iso': typeof IsoRoute
  '/secret-word': typeof SecretWordRoute
  '/sokoban': typeof SokobanRoute
  '/spring': typeof SpringRoute
  '/tic-tac-toe': typeof TicTacToeRoute
  '/two-hard-things': typeof TwoHardThingsRoute
  '/words': typeof WordsRoute
  '/font-explorer/hex': typeof FontExplorerHexRoute
  '/os/ios': typeof OsIosRoute
  '/os/ios3': typeof OsIos3Route
  '/os/sonoma': typeof OsSonomaRoute
  '/os/win98': typeof OsWin98Route
  '/pixel-font/vibe-coded': typeof PixelFontVibeCodedRoute
  '/font-explorer': typeof FontExplorerIndexRoute
  '/pantry': typeof PantryIndexRoute
  '/pixel-font': typeof PixelFontIndexRoute
  '/font-explorer/tables/$unknownTable': typeof FontExplorerTablesUnknownTableRoute
  '/font-explorer/tables/FFTM': typeof FontExplorerTablesFFTMRoute
  '/font-explorer/tables': typeof FontExplorerTablesIndexRoute
  '/pantry/books': typeof PantryBooksIndexRoute
  '/pantry/recipes/$recipeId/edit': typeof PantryRecipesRecipeIdEditRouteRoute
  '/pantry/books/$bookId': typeof PantryBooksBookIdIndexRoute
  '/pantry/recipes/$recipeId': typeof PantryRecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chadgdp': typeof ChadgdpRouteRoute
  '/font-explorer': typeof FontExplorerRouteRouteWithChildren
  '/nested': typeof NestedRouteRoute
  '/boggle': typeof BoggleRoute
  '/calendar': typeof CalendarRoute
  '/cv': typeof CvRoute
  '/demo': typeof DemoRoute
  '/faker': typeof FakerRoute
  '/gb': typeof GbRoute
  '/iso': typeof IsoRoute
  '/secret-word': typeof SecretWordRoute
  '/sokoban': typeof SokobanRoute
  '/spring': typeof SpringRoute
  '/tic-tac-toe': typeof TicTacToeRoute
  '/two-hard-things': typeof TwoHardThingsRoute
  '/words': typeof WordsRoute
  '/font-explorer/hex': typeof FontExplorerHexRoute
  '/os/ios': typeof OsIosRoute
  '/os/ios3': typeof OsIos3Route
  '/os/sonoma': typeof OsSonomaRoute
  '/os/win98': typeof OsWin98Route
  '/pixel-font/vibe-coded': typeof PixelFontVibeCodedRoute
  '/font-explorer/': typeof FontExplorerIndexRoute
  '/pantry/': typeof PantryIndexRoute
  '/pixel-font/': typeof PixelFontIndexRoute
  '/font-explorer/tables/$unknownTable': typeof FontExplorerTablesUnknownTableRoute
  '/font-explorer/tables/FFTM': typeof FontExplorerTablesFFTMRoute
  '/font-explorer/tables/': typeof FontExplorerTablesIndexRoute
  '/pantry/books/': typeof PantryBooksIndexRoute
  '/pantry/recipes/$recipeId/edit': typeof PantryRecipesRecipeIdEditRouteRoute
  '/pantry/books/$bookId/': typeof PantryBooksBookIdIndexRoute
  '/pantry/recipes/$recipeId/': typeof PantryRecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chadgdp'
    | '/font-explorer'
    | '/nested'
    | '/boggle'
    | '/calendar'
    | '/cv'
    | '/demo'
    | '/faker'
    | '/gb'
    | '/iso'
    | '/secret-word'
    | '/sokoban'
    | '/spring'
    | '/tic-tac-toe'
    | '/two-hard-things'
    | '/words'
    | '/font-explorer/hex'
    | '/os/ios'
    | '/os/ios3'
    | '/os/sonoma'
    | '/os/win98'
    | '/pixel-font/vibe-coded'
    | '/font-explorer/'
    | '/pantry'
    | '/pixel-font'
    | '/font-explorer/tables/$unknownTable'
    | '/font-explorer/tables/FFTM'
    | '/font-explorer/tables'
    | '/pantry/books'
    | '/pantry/recipes/$recipeId/edit'
    | '/pantry/books/$bookId'
    | '/pantry/recipes/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chadgdp'
    | '/nested'
    | '/boggle'
    | '/calendar'
    | '/cv'
    | '/demo'
    | '/faker'
    | '/gb'
    | '/iso'
    | '/secret-word'
    | '/sokoban'
    | '/spring'
    | '/tic-tac-toe'
    | '/two-hard-things'
    | '/words'
    | '/font-explorer/hex'
    | '/os/ios'
    | '/os/ios3'
    | '/os/sonoma'
    | '/os/win98'
    | '/pixel-font/vibe-coded'
    | '/font-explorer'
    | '/pantry'
    | '/pixel-font'
    | '/font-explorer/tables/$unknownTable'
    | '/font-explorer/tables/FFTM'
    | '/font-explorer/tables'
    | '/pantry/books'
    | '/pantry/recipes/$recipeId/edit'
    | '/pantry/books/$bookId'
    | '/pantry/recipes/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/chadgdp'
    | '/font-explorer'
    | '/nested'
    | '/boggle'
    | '/calendar'
    | '/cv'
    | '/demo'
    | '/faker'
    | '/gb'
    | '/iso'
    | '/secret-word'
    | '/sokoban'
    | '/spring'
    | '/tic-tac-toe'
    | '/two-hard-things'
    | '/words'
    | '/font-explorer/hex'
    | '/os/ios'
    | '/os/ios3'
    | '/os/sonoma'
    | '/os/win98'
    | '/pixel-font/vibe-coded'
    | '/font-explorer/'
    | '/pantry/'
    | '/pixel-font/'
    | '/font-explorer/tables/$unknownTable'
    | '/font-explorer/tables/FFTM'
    | '/font-explorer/tables/'
    | '/pantry/books/'
    | '/pantry/recipes/$recipeId/edit'
    | '/pantry/books/$bookId/'
    | '/pantry/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChadgdpRouteRoute: typeof ChadgdpRouteRoute
  FontExplorerRouteRoute: typeof FontExplorerRouteRouteWithChildren
  NestedRouteRoute: typeof NestedRouteRoute
  BoggleRoute: typeof BoggleRoute
  CalendarRoute: typeof CalendarRoute
  CvRoute: typeof CvRoute
  DemoRoute: typeof DemoRoute
  FakerRoute: typeof FakerRoute
  GbRoute: typeof GbRoute
  IsoRoute: typeof IsoRoute
  SecretWordRoute: typeof SecretWordRoute
  SokobanRoute: typeof SokobanRoute
  SpringRoute: typeof SpringRoute
  TicTacToeRoute: typeof TicTacToeRoute
  TwoHardThingsRoute: typeof TwoHardThingsRoute
  WordsRoute: typeof WordsRoute
  OsIosRoute: typeof OsIosRoute
  OsIos3Route: typeof OsIos3Route
  OsSonomaRoute: typeof OsSonomaRoute
  OsWin98Route: typeof OsWin98Route
  PixelFontVibeCodedRoute: typeof PixelFontVibeCodedRoute
  PantryIndexRoute: typeof PantryIndexRoute
  PixelFontIndexRoute: typeof PixelFontIndexRoute
  PantryBooksIndexRoute: typeof PantryBooksIndexRoute
  PantryRecipesRecipeIdEditRouteRoute: typeof PantryRecipesRecipeIdEditRouteRoute
  PantryBooksBookIdIndexRoute: typeof PantryBooksBookIdIndexRoute
  PantryRecipesRecipeIdIndexRoute: typeof PantryRecipesRecipeIdIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chadgdp': {
      id: '/chadgdp'
      path: '/chadgdp'
      fullPath: '/chadgdp'
      preLoaderRoute: typeof ChadgdpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/font-explorer': {
      id: '/font-explorer'
      path: '/font-explorer'
      fullPath: '/font-explorer'
      preLoaderRoute: typeof FontExplorerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nested': {
      id: '/nested'
      path: '/nested'
      fullPath: '/nested'
      preLoaderRoute: typeof NestedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boggle': {
      id: '/boggle'
      path: '/boggle'
      fullPath: '/boggle'
      preLoaderRoute: typeof BoggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faker': {
      id: '/faker'
      path: '/faker'
      fullPath: '/faker'
      preLoaderRoute: typeof FakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gb': {
      id: '/gb'
      path: '/gb'
      fullPath: '/gb'
      preLoaderRoute: typeof GbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iso': {
      id: '/iso'
      path: '/iso'
      fullPath: '/iso'
      preLoaderRoute: typeof IsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret-word': {
      id: '/secret-word'
      path: '/secret-word'
      fullPath: '/secret-word'
      preLoaderRoute: typeof SecretWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sokoban': {
      id: '/sokoban'
      path: '/sokoban'
      fullPath: '/sokoban'
      preLoaderRoute: typeof SokobanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spring': {
      id: '/spring'
      path: '/spring'
      fullPath: '/spring'
      preLoaderRoute: typeof SpringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tic-tac-toe': {
      id: '/tic-tac-toe'
      path: '/tic-tac-toe'
      fullPath: '/tic-tac-toe'
      preLoaderRoute: typeof TicTacToeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-hard-things': {
      id: '/two-hard-things'
      path: '/two-hard-things'
      fullPath: '/two-hard-things'
      preLoaderRoute: typeof TwoHardThingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words': {
      id: '/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof WordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/font-explorer/hex': {
      id: '/font-explorer/hex'
      path: '/hex'
      fullPath: '/font-explorer/hex'
      preLoaderRoute: typeof FontExplorerHexRouteImport
      parentRoute: typeof FontExplorerRouteRoute
    }
    '/os/ios': {
      id: '/os/ios'
      path: '/os/ios'
      fullPath: '/os/ios'
      preLoaderRoute: typeof OsIosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/ios3': {
      id: '/os/ios3'
      path: '/os/ios3'
      fullPath: '/os/ios3'
      preLoaderRoute: typeof OsIos3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/sonoma': {
      id: '/os/sonoma'
      path: '/os/sonoma'
      fullPath: '/os/sonoma'
      preLoaderRoute: typeof OsSonomaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/win98': {
      id: '/os/win98'
      path: '/os/win98'
      fullPath: '/os/win98'
      preLoaderRoute: typeof OsWin98RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pixel-font/vibe-coded': {
      id: '/pixel-font/vibe-coded'
      path: '/pixel-font/vibe-coded'
      fullPath: '/pixel-font/vibe-coded'
      preLoaderRoute: typeof PixelFontVibeCodedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/font-explorer/': {
      id: '/font-explorer/'
      path: '/'
      fullPath: '/font-explorer/'
      preLoaderRoute: typeof FontExplorerIndexRouteImport
      parentRoute: typeof FontExplorerRouteRoute
    }
    '/pantry/': {
      id: '/pantry/'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pixel-font/': {
      id: '/pixel-font/'
      path: '/pixel-font'
      fullPath: '/pixel-font'
      preLoaderRoute: typeof PixelFontIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/font-explorer/tables/$unknownTable': {
      id: '/font-explorer/tables/$unknownTable'
      path: '/tables/$unknownTable'
      fullPath: '/font-explorer/tables/$unknownTable'
      preLoaderRoute: typeof FontExplorerTablesUnknownTableRouteImport
      parentRoute: typeof FontExplorerRouteRoute
    }
    '/font-explorer/tables/FFTM': {
      id: '/font-explorer/tables/FFTM'
      path: '/tables/FFTM'
      fullPath: '/font-explorer/tables/FFTM'
      preLoaderRoute: typeof FontExplorerTablesFFTMRouteImport
      parentRoute: typeof FontExplorerRouteRoute
    }
    '/font-explorer/tables/': {
      id: '/font-explorer/tables/'
      path: '/tables'
      fullPath: '/font-explorer/tables'
      preLoaderRoute: typeof FontExplorerTablesIndexRouteImport
      parentRoute: typeof FontExplorerRouteRoute
    }
    '/pantry/books/': {
      id: '/pantry/books/'
      path: '/pantry/books'
      fullPath: '/pantry/books'
      preLoaderRoute: typeof PantryBooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry/recipes/$recipeId/edit': {
      id: '/pantry/recipes/$recipeId/edit'
      path: '/pantry/recipes/$recipeId/edit'
      fullPath: '/pantry/recipes/$recipeId/edit'
      preLoaderRoute: typeof PantryRecipesRecipeIdEditRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry/books/$bookId/': {
      id: '/pantry/books/$bookId/'
      path: '/pantry/books/$bookId'
      fullPath: '/pantry/books/$bookId'
      preLoaderRoute: typeof PantryBooksBookIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry/recipes/$recipeId/': {
      id: '/pantry/recipes/$recipeId/'
      path: '/pantry/recipes/$recipeId'
      fullPath: '/pantry/recipes/$recipeId'
      preLoaderRoute: typeof PantryRecipesRecipeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FontExplorerRouteRouteChildren {
  FontExplorerHexRoute: typeof FontExplorerHexRoute
  FontExplorerIndexRoute: typeof FontExplorerIndexRoute
  FontExplorerTablesUnknownTableRoute: typeof FontExplorerTablesUnknownTableRoute
  FontExplorerTablesFFTMRoute: typeof FontExplorerTablesFFTMRoute
  FontExplorerTablesIndexRoute: typeof FontExplorerTablesIndexRoute
}

const FontExplorerRouteRouteChildren: FontExplorerRouteRouteChildren = {
  FontExplorerHexRoute: FontExplorerHexRoute,
  FontExplorerIndexRoute: FontExplorerIndexRoute,
  FontExplorerTablesUnknownTableRoute: FontExplorerTablesUnknownTableRoute,
  FontExplorerTablesFFTMRoute: FontExplorerTablesFFTMRoute,
  FontExplorerTablesIndexRoute: FontExplorerTablesIndexRoute,
}

const FontExplorerRouteRouteWithChildren =
  FontExplorerRouteRoute._addFileChildren(FontExplorerRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChadgdpRouteRoute: ChadgdpRouteRoute,
  FontExplorerRouteRoute: FontExplorerRouteRouteWithChildren,
  NestedRouteRoute: NestedRouteRoute,
  BoggleRoute: BoggleRoute,
  CalendarRoute: CalendarRoute,
  CvRoute: CvRoute,
  DemoRoute: DemoRoute,
  FakerRoute: FakerRoute,
  GbRoute: GbRoute,
  IsoRoute: IsoRoute,
  SecretWordRoute: SecretWordRoute,
  SokobanRoute: SokobanRoute,
  SpringRoute: SpringRoute,
  TicTacToeRoute: TicTacToeRoute,
  TwoHardThingsRoute: TwoHardThingsRoute,
  WordsRoute: WordsRoute,
  OsIosRoute: OsIosRoute,
  OsIos3Route: OsIos3Route,
  OsSonomaRoute: OsSonomaRoute,
  OsWin98Route: OsWin98Route,
  PixelFontVibeCodedRoute: PixelFontVibeCodedRoute,
  PantryIndexRoute: PantryIndexRoute,
  PixelFontIndexRoute: PixelFontIndexRoute,
  PantryBooksIndexRoute: PantryBooksIndexRoute,
  PantryRecipesRecipeIdEditRouteRoute: PantryRecipesRecipeIdEditRouteRoute,
  PantryBooksBookIdIndexRoute: PantryBooksBookIdIndexRoute,
  PantryRecipesRecipeIdIndexRoute: PantryRecipesRecipeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
